// Generates `src/ui/landing/coverage.json` from the published ability data.
//
// The landing page IMPORTS that file rather than fetching it, so the figures are in the HTML at
// first paint — the page's central claim should not pop in after a request.
//
// THE GENERATED FILE IS COMMITTED, WHICH IS ONLY SAFE BECAUSE A TEST RE-DERIVES IT.
// `src/ui/landing/coverage.test.ts` recounts from `public/data/` on every run and fails if the
// committed figures differ by one. A generated file nobody re-derives is a hand-typed file with
// extra steps.
//
// Run by `npm run build` before Vite, and by `npm run build:coverage` on its own.

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { summariseCoverage, coverageAddsUp, type CoverageEntry } from '../../src/ui/coverage/coverage.ts';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const ABILITY_DIR = join(REPO, 'public', 'data', 'abilities');
const OUT = join(REPO, 'src', 'ui', 'coverage', 'coverage.json');
const README = join(REPO, 'README.md');

/** The README's coverage block, between its markers. Markdown cannot import JSON, so it is
 *  GENERATED rather than typed — the same rule the landing page follows, by the same script. */
export function readmeBlock(c: ReturnType<typeof summariseCoverage>): string {
  return [
    `On patch ${c.patch}, across ${c.abilities} ability entries and ${c.champions} champions:`,
    '',
    '| | |',
    '|---:|---|',
    `| ${c.verified} | independently re-derived (\`verified\`) — shown |`,
    `| ${c.derived} | checked against the source three ways (\`derived\`) — shown |`,
    `| ${c.incomplete - c.permanentlyUnanswerable} | not yet modelled — **not shown**, and each says what is missing |`,
    `| ${c.permanentlyUnanswerable} | impossible to complete, because no source records the fact — **not shown** |`,
    `| ${c.noDamage} | deal no damage, so there is nothing to have evidence about |`,
    '',
    `**${c.incompleteWithReason} of the ${c.incomplete} refused abilities name what is missing**, not merely that`,
    'something is. An ability that cannot be modelled contributes nothing to a total and is named',
    'in the result it is missing from.',
  ].join('\n');
}

const START = '<!-- coverage:start — generated by `npm run build:coverage`. Do not edit by hand. -->';
const END = '<!-- coverage:end -->';

/** Splice the block into the README between its markers. Returns the new file contents. */
export function spliceReadme(readme: string, block: string): string {
  const from = readme.indexOf(START);
  const to = readme.indexOf(END);
  if (from === -1 || to === -1) {
    throw new Error('build-coverage: README.md is missing its coverage markers.');
  }
  return `${readme.slice(0, from + START.length)}\n${block}\n${readme.slice(to)}`;
}

export function readPublishedCoverage() {
  const files = readdirSync(ABILITY_DIR).filter((f) => f.endsWith('.json')).sort();
  const entries: CoverageEntry[] = [];
  for (const file of files) {
    const parsed = JSON.parse(readFileSync(join(ABILITY_DIR, file), 'utf8')) as {
      abilities: CoverageEntry[];
    };
    entries.push(...parsed.abilities);
  }
  const manifest = JSON.parse(
    readFileSync(join(REPO, 'public', 'data', 'manifest.json'), 'utf8'),
  ) as { patch: string };
  return summariseCoverage(entries, { patch: manifest.patch, champions: files.length });
}

const coverage = readPublishedCoverage();
if (!coverageAddsUp(coverage)) {
  throw new Error(`build-coverage: the four statuses do not account for all ${coverage.abilities} entries.`);
}
writeFileSync(OUT, `${JSON.stringify(coverage, null, 2)}\n`, 'utf8');
writeFileSync(README, spliceReadme(readFileSync(README, 'utf8'), readmeBlock(coverage)), 'utf8');
console.log(
  `build-coverage: ${coverage.abilities} abilities across ${coverage.champions} champions, patch ${coverage.patch} -> src/ui/coverage/coverage.json and README.md`,
);
