/**
 * THE 37 PER-TICK ENTRIES, READ (2026-08-14).
 *
 * Companion audit, one row per entry in plain English:
 * `build/proposed-curated/per-tick-reading.json`, regenerated by
 * `node scripts/extract/per-tick-audit.ts`.
 *
 * DATA-SOURCES §58 withdrew 37 ability entries to `incomplete` because a component of each states
 * a PER-TICK damage figure and nobody had read the sentence behind it. The label alone cannot
 * decide the question: `per Arrow`, `per Bullet`, `per Spin` and `per Wave` are the same field and
 * the opposite meaning — hits that land in one moment, which belong in the burst total.
 *
 * This file is the reading. One entry per withdrawn ability, each carrying:
 *   - `quote`     — the sentence the verdict rests on, in readable English.
 *   - `verbatim`  — the SAME sentence as it appears in the cached wikitext, markup and all.
 *                   `verifyQuotes()` proves every one of these is a literal substring of
 *                   `build/proposed-curated/ability-wikitext.json`, so a quote cannot be
 *                   paraphrased into saying something the source does not.
 *   - the arithmetic: the duration and the interval the source states, the tick count they imply,
 *     and the count actually stored in `hits`.
 *
 * TWO SEPARATE QUESTIONS, AND THEY ARE NOT ANSWERED TOGETHER.
 *
 *   1. IS IT RECURRING? Decided by the sentence. All 37 are — every one states an interval in
 *      seconds. Not one turned out to be the `per Arrow` shape. That is the finding.
 *   2. IS THE STORED COUNT A FULL-DURATION COUNT? A separate, stored fact, and 18 of the 37 fail
 *      it. `marked` is true only when BOTH hold.
 *
 * Why the second question gates the first. Marking a component moves its figure out of the burst
 * line and into the damage-over-time line — where the engine multiplies it by `hits` and states it
 * as the total across the full duration (SPECIFICATION §3.8). Gate 1 requires a count and `hits: 1`
 * satisfies it, so marking an entry whose real count is 30 would publish a thirtieth of the damage
 * as the whole burn. That is a plausible wrong number, which is the one outcome this project
 * exists to prevent. An entry that recurs but cannot state its count stays withdrawn, and the
 * reason travels with it.
 *
 * ADDING A MEMBER MEANS READING ITS SENTENCE. This table is not a pattern and must never become
 * one: a new member is a new row with its own quote, checked against the cache.
 */

import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
/** Repo root. */
export const ROOT = join(HERE, '..', '..');

/** Where the source sentences were cached. Read-only here; the harvester owns writing it. */
export const WIKITEXT_CACHE = 'build/proposed-curated/ability-wikitext.json';

/** Why a read entry is not marked as recurring even though its sentence says it recurs. */
export type CountVerdict =
  /** The source's duration divided by its interval equals the stored `hits`. Safe to mark. */
  | 'corroborated'
  /** The source states no duration at all — a toggle, an aura, a resource-fed channel. */
  | 'no-duration-stated'
  /** A duration and interval are stated, so a count exists, but `hits` is 1: it was never stored. */
  | 'count-not-stored'
  /** The source's own description and its own leveling row imply DIFFERENT counts. */
  | 'contested';

export interface PerTickRead {
  /** `champion/slot/abilityName`, the same key merge-proposal.ts uses. */
  key: string;
  /** RECURRING for all 37. Kept as a field so a future member cannot skip stating it. */
  verdict: 'recurring' | 'simultaneous' | 'source-silent';
  countVerdict: CountVerdict;
  /** The sentence, readable. This is what lands in `overTime.sourceSays` for a marked entry. */
  quote: string;
  /** The same sentence(s) as literal substrings of the cached wikitext. Checked, not trusted. */
  verbatim: string[];
  /** Seconds the source gives for the effect's duration; null when it states none. */
  durationSeconds: number | null;
  /** Seconds between ticks, as the source states it. */
  intervalSeconds: number;
  /** duration / interval, where both exist. */
  impliedTicks: number | null;
  /** What `hits` actually holds in the harvested entry today. */
  storedHits: number[];
  /** True only when verdict is 'recurring' AND countVerdict is 'corroborated'. */
  marked: boolean;
  /** Anything a reader of this table needs that the quote does not carry. */
  note?: string;
}

/** THE READ TABLE. 37 rows, ordered by champion so it diffs against the withdrawal list. */
export const PER_TICK_READS: readonly PerTickRead[] = [
  {
    key: 'Alistar/E/Trample',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Alistar tramples the ground around him every 0.5 seconds over 5 seconds, becoming ghosted and dealing magic damage to nearby enemies',
    verbatim: [
      'tramples the ground around him every {{fd|0.5}} seconds over 5 seconds, becoming {{tip|ghosted}} and dealing {{as|magic damage}} to nearby enemies',
    ],
    durationSeconds: 5,
    intervalSeconds: 0.5,
    impliedTicks: 10,
    storedHits: [10],
    marked: true,
    note: 'the stacking empowered attack is a separate component and is untouched — only the trample itself recurs',
  },
  {
    key: 'Amumu/W/Despair',
    verdict: 'recurring',
    countVerdict: 'no-duration-stated',
    quote:
      'Amumu cries a continuous pool of tears, dealing magic damage every 0.5 seconds to nearby enemies',
    verbatim: [
      'cries a continuous pool of tears, dealing {{as|magic damage}} every {{fd|0.5}} seconds to nearby enemies',
    ],
    durationSeconds: null,
    intervalSeconds: 0.5,
    impliedTicks: null,
    storedHits: [1],
    marked: false,
    note: 'a toggle. It runs until the mana runs out, so no duration exists to divide and no full-duration total can be stated',
  },
  {
    key: 'Anivia/R/Glacial Storm',
    verdict: 'recurring',
    countVerdict: 'no-duration-stated',
    quote:
      'Anivia calls forth a driving rain of ice and hail at the target location, dealing magic damage every 0.5 seconds to enemies within',
    verbatim: [
      'dealing {{as|magic damage}} every {{fd|0.5}} seconds to enemies within and {{tip|slow|slowing}} them for 1 second',
    ],
    durationSeconds: null,
    intervalSeconds: 0.5,
    impliedTicks: null,
    storedHits: [1, 1],
    marked: false,
    note: 'a toggle, so no duration. Both components — the normal tick and the 300% empowered tick — recur, and the empowered one only begins once the blizzard reaches full size',
  },
  {
    key: 'Aurelion Sol/Q/Breath of Light',
    verdict: 'recurring',
    countVerdict: 'count-not-stored',
    quote:
      'the beam collides with the first enemy hit to burn them, dealing magic damage to them and surrounding enemies every 0.125 seconds',
    verbatim: [
      'dealing {{as|magic damage}} to them and surrounding enemies every {{fd|0.125}} seconds. Secondary targets are dealt 50% damage.',
      '{{tip|channel|charges}} for up to {{fd|3.25}} seconds to exhale a beam of starfire',
    ],
    durationSeconds: 3.25,
    intervalSeconds: 0.125,
    impliedTicks: 26,
    storedHits: [1, 1],
    marked: false,
    note: "THE COUNT IS RANK-DEPENDENT and cannot be one number: the source's own total row is labelled 'Ranks 1-4' and uses 26 ticks, while at rank 5 the channel duration is increased to 160 seconds. A single `hits` value would be wrong at one rank or the other",
  },
  {
    key: 'Aurelion Sol/E/Singularity',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Aurelion Sol conjures a black hole at the target location that lasts for 5 seconds, dealing magic damage every 0.25 seconds to enemies within',
    verbatim: [
      'that lasts for 5 seconds, granting {{tip|sight}} of the area and dealing {{as|magic damage}} every {{fd|0.25}} seconds to enemies within',
    ],
    durationSeconds: 5,
    intervalSeconds: 0.25,
    impliedTicks: 20,
    storedHits: [20],
    marked: true,
  },
  {
    key: 'Cassiopeia/Q/Noxious Blast',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'enemies within the blast are poisoned for 3 seconds, taking magic damage every 3/7 seconds over the duration',
    verbatim: [
      'are {{tip|poison|poisoned}} for 3 seconds, taking {{as|magic damage}} every {{ap|3/7|round=3}} seconds over the duration',
      'damage / 7 ticks rounded down to the nearest integer',
    ],
    durationSeconds: 3,
    intervalSeconds: 3 / 7,
    impliedTicks: 7,
    storedHits: [7],
    marked: true,
    note: "the page states the tick count twice — the interval implies 7 and the notes say '7 ticks' outright",
  },
  {
    key: 'Corki/W/Valkyrie',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'each blazing patch lasts 2.5 seconds, and enemies within the patches are dealt magic damage every 0.5 seconds',
    verbatim: [
      'Each patch lasts {{fd|2.5}} seconds.',
      'Enemies within the patches are dealt {{as|magic damage}} every {{fd|0.5}} seconds, lingering for 1 second.',
    ],
    durationSeconds: 2.5,
    intervalSeconds: 0.5,
    impliedTicks: 5,
    storedHits: [5],
    marked: true,
    note: "5 ticks is ONE patch. The dash drops up to 3 patches, but a target standing in one takes one patch's worth; the source gives no count for overlapping patches",
  },
  {
    key: 'Corki/E/Gatling Gun',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Corki sprays bullets in a cone toward his facing direction for 4 seconds, dealing physical damage every 0.25 seconds to all enemies hit',
    verbatim: [
      'sprays bullets in a cone toward his facing direction for 4 seconds, dealing {{as|physical damage}} every {{fd|0.25}} seconds to all enemies hit',
    ],
    durationSeconds: 4,
    intervalSeconds: 0.25,
    impliedTicks: 16,
    storedHits: [16],
    marked: true,
  },
  {
    key: 'Dr. Mundo/W/Heart Zapper',
    verdict: 'recurring',
    countVerdict: 'contested',
    quote:
      'Dr. Mundo charges up a defibrillator for up to 3 seconds, dealing magic damage every 0.25 seconds to nearby enemies',
    verbatim: [
      'charges up a defibrillator for up to 3 seconds, dealing {{as|magic damage}} every {{fd|0.25}} seconds to nearby enemies',
      '{{st|Magic Damage per Tick|{{ap|5 to 20}}|Total Magic Damage|{{ap|5*16 to 20*16}}}}',
    ],
    durationSeconds: 3,
    intervalSeconds: 0.25,
    impliedTicks: 12,
    storedHits: [16],
    marked: false,
    note: "THE SOURCE DISAGREES WITH ITSELF: 3 seconds at 0.25 gives 12 ticks, but its own total row multiplies the per-tick figure by 16. The page also notes 'Heart Zapper will occasionally deal an additional tick of damage' as a bug. Surfaced, not reconciled",
  },
  {
    key: 'Fiddlesticks/R/Crowstorm',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'a murder of crows flies wildly around the target location for 5 seconds, dealing magic damage every 0.25 seconds to nearby enemies',
    verbatim: [
      'with a murder of crows flying wildly around it for 5 seconds, dealing {{as|magic damage}} every {{fd|0.25}} seconds to nearby enemies',
    ],
    durationSeconds: 5,
    intervalSeconds: 0.25,
    impliedTicks: 20,
    storedHits: [20],
    marked: true,
  },
  {
    key: 'Hecarim/W/Spirit of Dread',
    verdict: 'recurring',
    countVerdict: 'contested',
    quote:
      'Hecarim surrounds himself with the Spirit of Dread for 4 seconds, dealing magic damage every second to nearby enemies',
    verbatim: [
      'surrounds himself with the Spirit of Dread for 4 seconds, dealing {{as|magic damage}} every second to nearby enemies',
      '{{st|Magic Damage Per Tick|{{ap|20 to 60}} {{as|(+ 20% AP)}}|Total Magic Damage|{{ap|20*5 to 60*5}}',
    ],
    durationSeconds: 4,
    intervalSeconds: 1,
    impliedTicks: 4,
    storedHits: [5],
    marked: false,
    note: 'THE SOURCE DISAGREES WITH ITSELF by one tick: 4 seconds at 1 second gives 4, its own total row multiplies by 5 (an initial tick plus four would explain it, but the page never says so). One tick of five is a fifth of the ability',
  },
  {
    key: 'Hwei/Q/Molten Fissure',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'a fissure lasts for 2.5 seconds, dealing magic damage every 0.25 seconds to enemies within the area',
    verbatim: [
      'A fissure lasts for {{fd|2.5}} seconds, dealing {{as|magic damage}} every {{fd|0.25}} seconds to enemies within the area',
    ],
    durationSeconds: 2.5,
    intervalSeconds: 0.25,
    impliedTicks: 10,
    storedHits: [10],
    marked: true,
    note: "10 ticks is ONE fissure, which is the conservative reading. The page adds that 'Enemies may be damaged by multiple fissures at once' but gives no count for how many overlap",
  },
  {
    key: 'Hwei/R/Spiraling Despair',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'the target is afflicted with an aura that grows over 3 seconds, and enemies within are dealt magic damage every 0.25 seconds',
    verbatim: [
      'afflicting them with an [[aura]] that grows over 3 seconds',
      "Enemies within are both dealt {{as|magic damage}} and applied a {{tip|stack}} of ''Despair'' every {{fd|0.25}} seconds.",
    ],
    durationSeconds: 3,
    intervalSeconds: 0.25,
    impliedTicks: 12,
    storedHits: [12],
    marked: true,
    note: 'the detonation at the end of the duration is a separate component and stays in the burst line',
  },
  {
    key: 'Jayce/W/Lightning Field',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Jayce surrounds himself with an electric field for 4 seconds that deals magic damage every second to nearby enemies',
    verbatim: [
      'surrounds himself with an electric field for 4 seconds that deals {{as|magic damage}} every second to nearby enemies',
    ],
    durationSeconds: 4,
    intervalSeconds: 1,
    impliedTicks: 4,
    storedHits: [4],
    marked: true,
  },
  {
    key: 'Karthus/E/Defile',
    verdict: 'recurring',
    countVerdict: 'no-duration-stated',
    quote:
      'Karthus surrounds himself in a necrotic aura that deals magic damage every 0.25 seconds to all nearby enemies',
    verbatim: [
      'surrounds himself in a necrotic [[aura]] that deals {{as|magic damage}} every {{fd|0.25}} seconds to all nearby enemies',
    ],
    durationSeconds: null,
    intervalSeconds: 0.25,
    impliedTicks: null,
    storedHits: [1],
    marked: false,
    note: 'a toggle held up by mana. The source gives a per-second figure and no duration, so there is no full-duration total to state',
  },
  {
    key: 'Malzahar/E/Malefic Visions',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      "Malzahar infects the target enemy's mind, dealing magic damage every 0.25 seconds over 4 seconds",
    verbatim: [
      "infects the target enemy's mind, dealing {{as|magic damage}} every {{fd|0.25}} seconds over 4 seconds",
    ],
    durationSeconds: 4,
    intervalSeconds: 0.25,
    impliedTicks: 16,
    storedHits: [16],
    marked: true,
    note: 'the duration refreshes on a further hit, so 16 is the count for one uninterrupted application — which is what the source states',
  },
  {
    key: 'Malzahar/R/Nether Grasp',
    verdict: 'recurring',
    countVerdict: 'count-not-stored',
    quote:
      'Malzahar channels for up to 2.5 seconds, dealing the target magic damage every 0.25 seconds, and a Null Zone lasting 5 seconds deals magic damage every 0.5 seconds to enemies within',
    verbatim: [
      'dealing them {{as|magic damage}} every {{fd|0.25}} seconds, {{tip|sight|revealing}} himself in the process',
      'that lasts 5 seconds, dealing {{as|magic damage}} every {{fd|0.5}} seconds to enemies within',
    ],
    durationSeconds: 2.5,
    intervalSeconds: 0.25,
    impliedTicks: 10,
    storedHits: [1, 1],
    marked: false,
    note: 'both components imply 10 ticks (2.5s/0.25s for the tether, 5s/0.5s for the Null Zone) and both store 1. The entry is refused from the merged file for a separate reason — its two rows share one component id — so marking it would change nothing today',
  },
  {
    key: 'Mel/E/Solar Snare',
    verdict: 'recurring',
    countVerdict: 'no-duration-stated',
    quote:
      'enemies within the field are dealt magic damage and slowed by 30% every 0.125 seconds, lingering for 0.25 seconds after exiting',
    verbatim: [
      'Enemies within the field are dealt {{as|magic damage}} and {{tip|slow|slowed}} by 30% every {{fd|0.125}} seconds, lingering for {{fd|0.25}} seconds after exiting.',
    ],
    durationSeconds: null,
    intervalSeconds: 0.125,
    impliedTicks: null,
    storedHits: [1],
    marked: false,
    note: "the field's own lifetime is never stated — the source gives a per-second figure (8 ticks) and the orb's 1.5-second root, neither of which is a field duration. Also refused from the merged file for two same-label rows",
  },
  {
    key: 'Miss Fortune/E/Make It Rain',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Miss Fortune casts a storm of bullets at the target location for 2 seconds, dealing magic damage every 0.25 seconds to enemies within',
    verbatim: [
      'casts a storm of bullets at the target location for 2 seconds, granting {{tip|sight}} of the area, dealing {{as|magic damage}} every {{fd|0.25}} seconds to enemies within',
    ],
    durationSeconds: 2,
    intervalSeconds: 0.25,
    impliedTicks: 8,
    storedHits: [8],
    marked: true,
  },
  {
    key: 'Morgana/W/Tormented Shadow',
    verdict: 'recurring',
    countVerdict: 'count-not-stored',
    quote:
      'the area becomes desecrated for 5 seconds, and enemies within take magic damage on-cast and every 0.5 seconds thereafter',
    verbatim: [
      'causing the area to become desecrated for 5 seconds. Enemies within take {{as|magic damage}} on-cast and every {{fd|0.5}} seconds thereafter',
    ],
    durationSeconds: 5,
    intervalSeconds: 0.5,
    impliedTicks: 10,
    storedHits: [1, 1],
    marked: false,
    note: "'on-cast AND every 0.5 seconds thereafter' reads as 11 instances while the source's own total row multiplies by 10. Both components store 1. A second question sits behind it: the minimum and maximum per-tick rows are the two ends of one missing-health scaling, not two damages to add",
  },
  {
    key: 'Naafiri/Q/Darkin Daggers',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'the dagger inflicts a bleed that deals bonus physical damage every 0.5 seconds over 5 seconds',
    verbatim: [
      "inflicts them with a {{as|bleed|buzzword3}} that deals {{as|'''bonus''' physical damage}} every {{fd|0.5}} seconds over 5 seconds",
    ],
    durationSeconds: 5,
    intervalSeconds: 0.5,
    impliedTicks: 10,
    storedHits: [10],
    marked: true,
    note: 'the initial dagger hit is a separate component and stays in the burst line',
  },
  {
    key: 'Nasus/E/Spirit Fire',
    verdict: 'recurring',
    countVerdict: 'contested',
    quote:
      'the fire remains for 5 seconds, dealing magic damage each second to enemies within and inflicting armor reduction',
    verbatim: [
      'The fire then remains for 5 seconds, dealing {{as|magic damage}} each second to enemies within',
      '{{st|Magic Damage Per Tick|{{ap|10 to 34}} {{as|(+ 12% AP)}}|Total Magic Damage|{{ap|10*10 to 34*10}}',
    ],
    durationSeconds: 5,
    intervalSeconds: 1,
    impliedTicks: 5,
    storedHits: [10],
    marked: false,
    note: 'THE SOURCE DISAGREES WITH ITSELF BY A FACTOR OF TWO: the description says each second for 5 seconds, which is 5 ticks; its own total row multiplies the per-tick figure by 10. One of the two is wrong and the page does not say which',
  },
  {
    key: 'Nasus/R/Fury of the Sands',
    verdict: 'recurring',
    countVerdict: 'count-not-stored',
    quote:
      'Nasus empowers himself for 15 seconds, and while empowered he deals magic damage every 0.5 seconds to nearby enemies',
    verbatim: [
      'empowers himself for 15 seconds',
      'he deals {{as|magic damage}} every {{fd|0.5}} seconds to nearby enemies, capped at 240 per second',
    ],
    durationSeconds: 15,
    intervalSeconds: 0.5,
    impliedTicks: 30,
    storedHits: [1],
    marked: false,
    note: 'the source states 30 ticks in its own total row and the entry stores 1, so marking it would publish a thirtieth of the burn. The per-second cap of 240 is a further modifier nothing models yet',
  },
  {
    key: 'Nidalee/W/Bushwhack',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'the trap springs upon contact with an enemy, dealing magic damage every second over 4 seconds',
    verbatim: [
      'The trap will spring upon contact with an enemy, dealing {{as|magic damage}} every second over 4 seconds.',
    ],
    durationSeconds: 4,
    intervalSeconds: 1,
    impliedTicks: 4,
    storedHits: [4],
    marked: true,
  },
  {
    key: 'Nocturne/E/Unspeakable Horror',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Nocturne forms a tether between himself and the target for 2 seconds, during which the target takes magic damage every 0.5 seconds over the duration',
    verbatim: [
      'forming a {{tip|tether}} between himself and the target for 2 seconds, during which the target takes {{as|magic damage}} every {{fd|0.5}} seconds over the duration',
    ],
    durationSeconds: 2,
    intervalSeconds: 0.5,
    impliedTicks: 4,
    storedHits: [4],
    marked: true,
  },
  {
    key: 'Ornn/W/Bellows Breath',
    verdict: 'recurring',
    countVerdict: 'count-not-stored',
    quote:
      'over the 0.75-second march Ornn belches fire over a cone in front of him, dealing magic damage every 0.15 seconds to enemies hit',
    verbatim: [
      '{{tip|lunge|marches}} forward in the target direction over {{fd|0.75}} seconds',
      'he belches fire over a cone in front of him, dealing {{as|magic damage}} every {{fd|0.15}} seconds to enemies hit',
    ],
    durationSeconds: 0.75,
    intervalSeconds: 0.15,
    impliedTicks: 5,
    storedHits: [1],
    marked: false,
    note: "BORDERLINE AND WORTH A DECISION: the five ticks land inside a single 0.75-second lunge, which is a sweep rather than a burn, and the wiki tags the ability 'aoe' where every other entry in this population is tagged 'aoedot'. It stays withdrawn on the count alone, so the borderline never had to be resolved here",
  },
  {
    key: 'Rell/R/Magnet Storm',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Rell creates a gravitational field around her for the next 2 seconds that deals magic damage every 0.25 seconds to nearby enemies',
    verbatim: [
      'creating a gravitational field around her for the next 2 seconds that deals {{as|magic damage}} every {{fd|0.25}} seconds to nearby enemies',
    ],
    durationSeconds: 2,
    intervalSeconds: 0.25,
    impliedTicks: 8,
    storedHits: [8],
    marked: true,
  },
  {
    key: 'Renekton/R/Dominus',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Renekton empowers himself for 15 seconds, and during this time he deals magic damage every 0.5 seconds to nearby enemies',
    verbatim: [
      "'''Renekton''' empowers himself for 15 seconds",
      'he deals {{as|magic damage}} every {{fd|0.5}} seconds to nearby enemies and generates {{as|5 Fury}} per second',
    ],
    durationSeconds: 15,
    intervalSeconds: 0.5,
    impliedTicks: 30,
    storedHits: [30],
    marked: true,
    note: 'all 30 ticks were publishing as BURST damage before the withdrawal, which is the single largest figure this reading moves',
  },
  {
    key: 'Rumble/Q/Flamespitter',
    verdict: 'recurring',
    countVerdict: 'count-not-stored',
    quote:
      'Rumble activates his flamethrower for 3 seconds, spewing forth flames in a frontal cone every 0.25 seconds, and enemies hit are scorched, taking magic damage every 0.25 seconds',
    verbatim: [
      'activate his flamethrower for 3 seconds, spewing forth flames in a {{tt|frontal|In his facing direction}} cone every {{fd|0.25}} seconds',
      'Values are defined OVER 3 SECONDS',
    ],
    durationSeconds: 3,
    intervalSeconds: 0.25,
    impliedTicks: 12,
    storedHits: [1, 1],
    marked: false,
    note: "the page's own editing note says its values are defined over 3 seconds and its rows divide by 12, but it also states a MAXIMUM of 15/12 — the scorch outlives the cast. Both the normal and the Danger Zone component store 1",
  },
  {
    key: 'Rumble/R/The Equalizer',
    verdict: 'recurring',
    countVerdict: 'count-not-stored',
    quote:
      'enemies struck by the impact or within the field are marked Burning for 1 second, taking magic damage every 0.25 seconds, and may be Burning for up to 5 seconds, for a total of 20 instances of its effect',
    verbatim: [
      "are marked ''Burning'' for 1 second, taking {{as|magic damage}} every {{fd|0.25}} seconds",
      "Enemies may be ''Burning'' for up to 5 seconds, for a total of 20 instances of its effect.",
    ],
    durationSeconds: 5,
    intervalSeconds: 0.25,
    impliedTicks: 20,
    storedHits: [1],
    marked: false,
    note: "ACTIONABLE: the source states the count in words — 'a total of 20 instances' — and the harvester stored 1. This one needs no further reading, only capturing",
  },
  {
    key: 'Singed/Q/Poison Trail',
    verdict: 'recurring',
    countVerdict: 'count-not-stored',
    quote:
      'the poisoned target takes magic damage every 0.25 seconds over 2 seconds as well as upon being hit if not currently affected',
    verbatim: [
      'The target takes {{as|magic damage}} every {{fd|0.25}} seconds over 2 seconds as well as upon being hit if not currently affected.',
    ],
    durationSeconds: 2,
    intervalSeconds: 0.25,
    impliedTicks: 8,
    storedHits: [1],
    marked: false,
    note: "the source's own minimum-damage row multiplies the per-tick figure by 8, so the count exists and was not stored. The cloud refreshes the poison while Singed keeps walking, so 8 is a floor rather than a fixed total",
  },
  {
    key: 'Swain/R/Demonic Ascension',
    verdict: 'recurring',
    countVerdict: 'no-duration-stated',
    quote:
      'Swain drains the lifeforce of nearby enemies, both dealing magic damage and healing himself every 0.5 seconds per target affected',
    verbatim: [
      'drains the lifeforce of nearby enemies, both dealing {{as|magic damage}} and {{tip|healing}} himself every {{fd|0.5}} seconds per target affected',
    ],
    durationSeconds: null,
    intervalSeconds: 0.5,
    impliedTicks: null,
    storedHits: [1],
    marked: false,
    note: 'the duration is fed by Demonic Energy, which decays at one rate, then faster after 5 seconds, and refills on a takedown. No fixed duration exists to divide — this is the one entry where the count is not merely unstored but unstatable from the source',
  },
  {
    key: 'Udyr/R/Wingborne Storm',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Udyr summons a blizzard around himself for 4 seconds that deals magic damage every 0.5 seconds to nearby enemies',
    verbatim: [
      'summons a blizzard around himself for 4 seconds that deals {{as|magic damage}} every {{fd|0.5}} seconds to nearby enemies',
    ],
    durationSeconds: 4,
    intervalSeconds: 0.5,
    impliedTicks: 8,
    storedHits: [8],
    marked: true,
    note: "the Awakened recast's maximum-health bonus is stated per tick as well, and is not part of this component",
  },
  {
    key: 'Viktor/R/Arcane Storm',
    verdict: 'recurring',
    countVerdict: 'count-not-stored',
    quote:
      'the singularity remains active as a moving storm for 6.5 seconds, striking a bolt of electricity onto enemies within it every second to deal magic damage',
    verbatim: [
      'The singularity then remains active as a moving storm for {{fd|6.5}} seconds, striking a bolt of electricity onto enemies within it every second to deal {{as|magic damage}}',
      'The base duration allows for 7 strikes (including the initial one).',
    ],
    durationSeconds: 6.5,
    intervalSeconds: 1,
    impliedTicks: 6,
    storedHits: [1],
    marked: false,
    note: "ACTIONABLE: the page states '7 strikes (including the initial one)', and the initial strike is a separate component, so this one is 6. The count was not stored because the total row folds the initial hit in and the harvester's division rule could not apply",
  },
  {
    key: 'Vladimir/W/Sanguine Pool',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Vladimir sinks into a pool of blood for 2 seconds, and enemies within the pool are dealt magic damage every 0.5 seconds over the duration',
    verbatim: [
      'becoming {{tip|untargetable}} and {{tip|ghosted}} for 2 seconds',
      'Enemies within the pool are dealt {{as|magic damage}} every {{fd|0.5}} seconds over the duration',
    ],
    durationSeconds: 2,
    intervalSeconds: 0.5,
    impliedTicks: 4,
    storedHits: [4],
    marked: true,
    note: "the page's notes confirm the shape: the first tick damages immediately so the final one occurs 0.5 seconds before Vladimir becomes targetable again",
  },
  {
    key: 'Wukong/R/Cyclone',
    verdict: 'recurring',
    countVerdict: 'count-not-stored',
    quote:
      'Wukong spins his staff around for up to 2 seconds, and the staff deals physical damage every 0.25 seconds to enemies hit',
    verbatim: [
      'spins his staff around for up to 2 seconds',
      'The staff deals {{as|physical damage}} every {{fd|0.25}} seconds to enemies hit',
    ],
    durationSeconds: 2,
    intervalSeconds: 0.25,
    impliedTicks: 8,
    storedHits: [1],
    marked: false,
    note: "the source's total row divides by 8, so the count exists and was not stored. Like Ornn W this is a spin rather than a burn, and whether a 2-second channel belongs in the damage-over-time line is a decision for the lead rather than this reading",
  },
  {
    key: 'Yunara/W/Arc of Judgment',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'upon reaching maximum range the bead expands and lingers in place for 1 second, and while lingering it deals a share of the impact damage as magic damage to nearby enemies every 0.25 seconds',
    verbatim: [
      'it will expand and linger in place for 1 second regardless of enemies hit',
      'the bead deals {{#expr:{{#var:lm}}*100/4}}% of the impact damage as {{as|magic damage}} to nearby enemies every {{fd|0.25}} seconds',
    ],
    durationSeconds: 1,
    intervalSeconds: 0.25,
    impliedTicks: 4,
    storedHits: [4],
    marked: true,
    note: "the 1-second linger is the only duration the source fixes; the in-flight linger resets its remaining duration and has no stated length, so 4 is the count for the expanded bead",
  },
];

/** The entries this reading marks as recurring, as `key -> the sentence it rests on`. */
export function markedOverTime(): ReadonlyMap<string, string> {
  return new Map(PER_TICK_READS.filter((r) => r.marked).map((r) => [r.key, r.quote]));
}

/**
 * A MARKED ROW MUST BE RECURRING AND ITS COUNT CORROBORATED. Nothing else may be marked.
 *
 * The rule the table is written to, restated as a check so a later edit cannot quietly break it:
 * marking a row whose count is contested or unstored publishes a wrong burn total.
 */
export function checkMarkRule(reads: readonly PerTickRead[] = PER_TICK_READS): string[] {
  const wrong: string[] = [];
  for (const r of reads) {
    const eligible = r.verdict === 'recurring' && r.countVerdict === 'corroborated';
    if (r.marked && !eligible) {
      wrong.push(`${r.key}: marked, but it is ${r.verdict} with a ${r.countVerdict} count`);
    }
    if (!r.marked && eligible) {
      wrong.push(`${r.key}: recurring with a corroborated count, but not marked`);
    }
    if (r.marked && !r.quote) wrong.push(`${r.key}: marked with no quote`);
    if (r.countVerdict === 'corroborated' && r.impliedTicks !== r.storedHits[0]) {
      wrong.push(
        `${r.key}: called corroborated, but ${r.durationSeconds}s / ${r.intervalSeconds}s = ` +
          `${r.impliedTicks} and hits is ${r.storedHits[0]}`,
      );
    }
  }
  return wrong;
}

/** The four read before these 37 (DATA-SOURCES §58.3). Not part of this reading. */
export const ALREADY_READ: ReadonlySet<string> = new Set([
  'Fizz/W/Seastone Trident',
  'Teemo/E/Toxic Shot',
  'Teemo/R/Noxious Trap',
  'Nilah/R/Apotheosis',
]);

/** The same test merge-proposal.ts uses to find a per-tick component. */
export const PER_TICK_LABEL = /per\s*tick/i;

/** The shape this table needs from a harvested ability. Narrower than `CuratedAbility` on purpose:
 *  the reading depends on identity, the component labels and the hit counts, and on nothing else. */
export interface HarvestedShape {
  champion: string;
  slot: string;
  abilityName: string;
  components: Array<{ label?: string | undefined; hits?: number | undefined }>;
}

/**
 * THE TABLE MUST DESCRIBE THE REAL POPULATION, NOT A REMEMBERED ONE.
 *
 * Three ways a hand-read table goes wrong once the data moves under it, and all three are worse
 * than having no table, because a stale row reads exactly like a checked one:
 *   - an entry acquires a per-tick component and nobody reads it;
 *   - a row survives for an entry that no longer has one;
 *   - a hit count changes and the arithmetic in the row now describes nothing.
 */
export function checkAgainstHarvest(
  reads: readonly PerTickRead[],
  abilities: readonly HarvestedShape[],
): string[] {
  const out: string[] = [];
  const id = (a: HarvestedShape): string => `${a.champion}/${a.slot}/${a.abilityName}`;
  const population = abilities.filter(
    (a) => a.components.some((c) => PER_TICK_LABEL.test(c.label ?? '')) && !ALREADY_READ.has(id(a)),
  );
  const tableKeys = new Set(reads.map((r) => r.key));
  for (const a of population) {
    if (!tableKeys.has(id(a))) out.push(`${id(a)}: carries a per-tick component and nobody read it`);
  }
  for (const k of tableKeys) {
    if (!population.some((a) => id(a) === k)) out.push(`${k}: read, but it is not in the population`);
  }
  for (const r of reads) {
    const a = population.find((x) => id(x) === r.key);
    if (!a) continue;
    const actual = a.components
      .filter((c) => PER_TICK_LABEL.test(c.label ?? ''))
      .map((c) => c.hits ?? null);
    if (JSON.stringify(actual) !== JSON.stringify(r.storedHits)) {
      out.push(
        `${r.key}: the reading says hits ${JSON.stringify(r.storedHits)}, the harvest holds ` +
          `${JSON.stringify(actual)}`,
      );
    }
  }
  return out;
}

export interface QuoteCheck {
  key: string;
  found: number;
  missing: string[];
  pageMissing: boolean;
}

/** A cached source page, as `ability-wikitext.json` stores it. */
export interface CachedPage {
  champion: string;
  slot: string;
  abilityName: string;
  wikitext: string;
}

/**
 * PROVE EVERY QUOTE IS REALLY IN THE SOURCE.
 *
 * Each `verbatim` fragment must appear as a literal substring of the ability's cached wikitext.
 * A paraphrase that drifted, or a sentence attributed to the wrong ability, fails here.
 */
export function verifyQuotes(
  reads: readonly PerTickRead[],
  pages: readonly CachedPage[],
): QuoteCheck[] {
  const byKey = new Map(pages.map((p) => [`${p.champion}/${p.slot}/${p.abilityName}`, p.wikitext]));
  return reads.map((r) => {
    const text = byKey.get(r.key);
    if (text === undefined) return { key: r.key, found: 0, missing: r.verbatim, pageMissing: true };
    const missing = r.verbatim.filter((v) => !text.includes(v));
    return { key: r.key, found: r.verbatim.length - missing.length, missing, pageMissing: false };
  });
}

/** Read the wikitext cache. Separated from `verifyQuotes` so the check itself needs no disk. */
export async function loadPages(): Promise<CachedPage[]> {
  const raw = await readFile(join(ROOT, WIKITEXT_CACHE), 'utf8');
  return (JSON.parse(raw) as { pages: CachedPage[] }).pages;
}
