/**
 * THE 37 PER-TICK ENTRIES, READ (2026-08-14).
 *
 * Companion audit, one row per entry in plain English:
 * `build/proposed-curated/per-tick-reading.json`, regenerated by
 * `node scripts/extract/per-tick-audit.ts`.
 *
 * DATA-SOURCES §58 withdrew 37 ability entries to `incomplete` because a component of each states
 * a PER-TICK damage figure and nobody had read the sentence behind it. The label alone cannot
 * decide the question: `per Arrow`, `per Bullet`, `per Spin` and `per Wave` are the same field and
 * the opposite meaning — hits that land in one moment, which belong in the burst total.
 *
 * This file is the reading. One entry per withdrawn ability, each carrying:
 *   - `quote`     — the sentence the verdict rests on, in readable English.
 *   - `verbatim`  — the SAME sentence as it appears in the cached wikitext, markup and all.
 *                   `verifyQuotes()` proves every one of these is a literal substring of
 *                   `build/proposed-curated/ability-wikitext.json`, so a quote cannot be
 *                   paraphrased into saying something the source does not.
 *   - the arithmetic: the duration and the interval the source states, the tick count they imply,
 *     and the count actually stored in `hits`.
 *
 * TWO SEPARATE QUESTIONS, AND THEY ARE NOT ANSWERED TOGETHER.
 *
 *   1. IS IT RECURRING? Decided by the sentence. All 37 are — every one states an interval in
 *      seconds. Not one turned out to be the `per Arrow` shape. That is the finding.
 *   2. IS THE STORED COUNT A FULL-DURATION COUNT? A separate, stored fact. 18 of the 37 failed it
 *      when this table was written on 2026-08-14. **4 were corrected on 2026-08-15 and 2 more in
 *      the re-read the same day**, so 12 fail it today. `marked` is true only when BOTH hold.
 *
 * THE SIX CORRECTED ON 2026-08-15, and they are two different things:
 *
 *   - CAPTURED — Rumble R (20), Viktor R (6), and from the re-read Nasus R (30) and Wukong R (8).
 *     The harvest stored 1; the page PRINTS the count, in words or in its own total-row
 *     multiplier, and the printed count equals the arithmetic.
 *   - SETTLED — Hecarim W (4, not the stored 5) and Dr. Mundo W (12, not the stored 16). The page
 *     contradicts ITSELF, and Riot's own patch notes — outside the wiki entirely — say which half
 *     is stale. DATA-SOURCES §59.
 *
 * NASUS E IS THE ONE THAT STAYED REFUSED, and it is the reason this table does not simply take
 * the description's arithmetic whenever the row disagrees. Its total is settled by Riot's patch
 * notes as firmly as Hecarim's is. Its INTERVAL is stated by nothing anywhere, so "5 ticks of
 * 10–34" and "10 ticks of 5–17" are both consistent with every reachable source, and a count
 * cannot be computed from a duration alone. It stays `contested` and unmarked BY DECISION.
 *
 * THE RE-READ OF 2026-08-15 FOUND FOUR THINGS BEYOND THE TWO CAPTURES, and three of them are
 * refusals rather than additions — which is the shape this work usually takes:
 *
 *   - Singed Q moved from `count-not-stored` to `contested`. Its page states 8 in its own minimum
 *     row and 9 in its description and notes together, and the same page's twin — Rumble Q, which
 *     carries the identical "one additional instance on application" note — DOES count that
 *     instance in its minimum row. So the two pages apply one rule two ways.
 *   - Ornn W and Malzahar R reconcile at 5 and at 10 and are still not captured. Neither blocker
 *     is in the source: Ornn W's is SPECIFICATION §3.8 (five gouts inside one 0.75-second lunge
 *     are not damage "following the combo") and Malzahar R's is our own harvest storing its two
 *     per-tick rows under one component id. `reconcilesAt` and `captureBlockedBy` record both.
 *   - Rumble Q states three counts — 3, 12 and 15 — and every one of them is right for a
 *     different situation. Its full-duration figure is 15 where its duration over its interval is
 *     12, so the capture rule refuses it, correctly.
 *
 * Why the second question gates the first. Marking a component moves its figure out of the burst
 * line and into the damage-over-time line — where the engine multiplies it by `hits` and states it
 * as the total across the full duration (SPECIFICATION §3.8). Gate 1 requires a count and `hits: 1`
 * satisfies it, so marking an entry whose real count is 30 would publish a thirtieth of the damage
 * as the whole burn. That is a plausible wrong number, which is the one outcome this project
 * exists to prevent. An entry that recurs but cannot state its count stays withdrawn, and the
 * reason travels with it.
 *
 * ADDING A MEMBER MEANS READING ITS SENTENCE. This table is not a pattern and must never become
 * one: a new member is a new row with its own quote, checked against the cache.
 */

import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
/** Repo root. */
export const ROOT = join(HERE, '..', '..');

/** Where the source sentences were cached. Read-only here; the harvester owns writing it. */
export const WIKITEXT_CACHE = 'build/proposed-curated/ability-wikitext.json';

/** Why a read entry is not marked as recurring even though its sentence says it recurs. */
export type CountVerdict =
  /** The source's duration divided by its interval equals the stored `hits`. Safe to mark. */
  | 'corroborated'
  /**
   * THE SOURCE STATES THE COUNT ITSELF, THE HARVESTER STORED 1, AND THE COUNT IS TAKEN FROM THE
   * SOURCE'S OWN WORDS (2026-08-15).
   *
   * Distinguished sharply from `count-not-stored`, which is where these two rows sat until today.
   * A `captured` row is one where the source does not merely make a count DERIVABLE from a
   * duration and an interval — it PRINTS one, in a sentence or in its own leveling-row formula —
   * and that printed count equals the arithmetic. Three statements have to agree before a row may
   * be captured, and `statedTotal` records the printed one:
   *
   *   1. the sentence's duration divided by the sentence's interval (`impliedTicks`);
   *   2. the count the source states in words or in its own total-row multiplier;
   *   3. and they must be the same number.
   *
   * Only then is `hits` corrected, at merge time, from 1 to the stated count — and the correction
   * is reported entry by entry rather than folded into a total. Capturing a count that reconciles
   * with nothing would publish a fraction of a burn as the whole of it, which is exactly what the
   * `count-not-stored` arm exists to refuse.
   */
  | 'captured'
  /**
   * THE PAGE CONTRADICTED ITSELF AND AN INDEPENDENT PRIMARY SOURCE DECIDED WHICH HALF IS RIGHT
   * (2026-08-15, DATA-SOURCES §59).
   *
   * A `settled` row began as `contested`: the description's duration and interval imply one count
   * and the page's own leveling row multiplies by another. Preferring the tidier half is exactly
   * what this project forbids, so neither was taken on the page's own authority. What moves a row
   * out of `contested` is evidence from OUTSIDE the wiki — in both current cases Riot's own patch
   * notes on leagueoflegends.com, which record the duration change the leveling row was never
   * updated for. `settledBy` names it.
   *
   * The same three statements as `captured` must still agree, and one more:
   *
   *   1. the sentence's duration divided by the sentence's interval (`impliedTicks`);
   *   2. the count `statedTotal.instances` claims;
   *   3. they must be the same number;
   *   4. and `settledBy` must name the source outside the cached page that decided it.
   *
   * WHAT NOTHING CHECKS MECHANICALLY: `settledBy`. `verifyQuotes` proves a fragment is literally in
   * the cached wikitext, and a patch note is not in the cached wikitext by definition. So a settled
   * row's `verbatim` is the WIKI SENTENCE the count is computed from — which is checked — while the
   * citation that broke the tie is prose a person has to follow. That asymmetry is stated here
   * rather than hidden, because it is the weakest link in a settled row.
   */
  | 'settled'
  /** The source states no duration at all — a toggle, an aura, a resource-fed channel. */
  | 'no-duration-stated'
  /**
   * A duration and interval are stated, so a count exists, but `hits` is 1: it was never stored.
   *
   * IT IS A STATEMENT ABOUT OUR DATA, NOT ABOUT THE SOURCE. A row here may sit anywhere on a
   * range: the source may print the count plainly (Ornn W divides three separate rows by 5) or
   * merely make it derivable. What separates such a row from `captured` is whether anything
   * BLOCKS acting on it — and where the count does reconcile and the row is still not captured,
   * `reconcilesAt` and `captureBlockedBy` must both be filled in, so the refusal is a stated
   * fact rather than an omission a later reader mistakes for unread work.
   */
  | 'count-not-stored'
  /** The source's own description and its own leveling row imply DIFFERENT counts. */
  | 'contested';

/**
 * THE COUNT A `captured` OR `settled` ROW CORRECTS THE HARVEST TO.
 *
 * `verbatim` must also appear in the row's `verbatim` list, so `verifyQuotes` proves it is a
 * literal substring of the cached wikitext — a corrected count rests on a checked sentence, never
 * on a reader's summary of one.
 */
export interface StatedTotal {
  /** The number of instances the source states for the component(s) named below. */
  instances: number;
  /** The `id` of every component this count applies to, as the harvest stored it. */
  componentIds: string[];
  /** How the source states it, in plain English, for the audit. */
  statedBy: string;
  /** The fragment of source text the count is read from. Also present in `verbatim`. */
  verbatim: string;
  /**
   * REQUIRED ON A `settled` ROW, FORBIDDEN ON A `captured` ONE. The evidence from outside the
   * cached page that decided which of the page's two self-contradicting halves is right — named
   * specifically enough that a reader can go and check it, because nothing here can.
   */
  settledBy?: string;
}

export interface PerTickRead {
  /** `champion/slot/abilityName`, the same key merge-proposal.ts uses. */
  key: string;
  /** RECURRING for all 37. Kept as a field so a future member cannot skip stating it. */
  verdict: 'recurring' | 'simultaneous' | 'source-silent';
  countVerdict: CountVerdict;
  /** The sentence, readable. This is what lands in `overTime.sourceSays` for a marked entry. */
  quote: string;
  /** The same sentence(s) as literal substrings of the cached wikitext. Checked, not trusted. */
  verbatim: string[];
  /** Seconds the source gives for the effect's duration; null when it states none. */
  durationSeconds: number | null;
  /** Seconds between ticks, as the source states it. */
  intervalSeconds: number;
  /** duration / interval, where both exist. */
  impliedTicks: number | null;
  /**
   * What `hits` actually holds in THE HARVESTED ENTRY today — not what the merge writes.
   *
   * A `captured` or `settled` row leaves this at what the harvest holds (1 for Rumble R and
   * Viktor R, the stale leveling-row multiplier for Hecarim W and Dr. Mundo W), because that is
   * what this field documents and what `checkAgainstHarvest` compares against. The corrected count
   * lives in `statedTotal.instances`, and the correction happens in the merge proposal, where it is
   * reported before and after.
   */
  storedHits: number[];
  /** Present only on a `captured` or `settled` row: the corrected count and where it comes from. */
  statedTotal?: StatedTotal;
  /**
   * THE COUNT A ROW RECONCILES AT WHILE STILL NOT BEING CAPTURED (2026-08-15).
   *
   * Added because two rows reached the same arithmetic as Rumble R and Viktor R — the source's
   * own duration over its own interval, printed by the page as well — and are still not written.
   * Recording them as plain `count-not-stored` said "a count exists somewhere in the source",
   * which reads as unread work and would send the next person to redo the reading.
   *
   * It must equal `impliedTicks`, and it may not appear without `captureBlockedBy`. A number
   * with no stated blocker is a capture somebody forgot to finish.
   */
  reconcilesAt?: number;
  /**
   * WHY A RECONCILING COUNT IS NOT WRITTEN. Required whenever `reconcilesAt` is present.
   *
   * Both current blockers are outside the source: one is a defect in our own harvest (two rows
   * sharing a component id, so no count can be attached to one of them), and one is a question
   * SPECIFICATION §3.8 does not answer (whether damage that lands entirely inside a 0.75-second
   * cast is "delivered following the combo"). Neither is a fact the wiki can supply.
   */
  captureBlockedBy?: string;
  /**
   * True only when verdict is 'recurring' AND countVerdict is 'corroborated', 'captured' or
   * 'settled'.
   */
  marked: boolean;
  /** Anything a reader of this table needs that the quote does not carry. */
  note?: string;
}

/** THE READ TABLE. 37 rows, ordered by champion so it diffs against the withdrawal list. */
export const PER_TICK_READS: readonly PerTickRead[] = [
  {
    key: 'Alistar/E/Trample',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Alistar tramples the ground around him every 0.5 seconds over 5 seconds, becoming ghosted and dealing magic damage to nearby enemies',
    verbatim: [
      'tramples the ground around him every {{fd|0.5}} seconds over 5 seconds, becoming {{tip|ghosted}} and dealing {{as|magic damage}} to nearby enemies',
    ],
    durationSeconds: 5,
    intervalSeconds: 0.5,
    impliedTicks: 10,
    storedHits: [10],
    marked: true,
    note: 'the stacking empowered attack is a separate component and is untouched — only the trample itself recurs',
  },
  {
    key: 'Amumu/W/Despair',
    verdict: 'recurring',
    countVerdict: 'no-duration-stated',
    quote:
      'Amumu cries a continuous pool of tears, dealing magic damage every 0.5 seconds to nearby enemies',
    verbatim: [
      'cries a continuous pool of tears, dealing {{as|magic damage}} every {{fd|0.5}} seconds to nearby enemies',
    ],
    durationSeconds: null,
    intervalSeconds: 0.5,
    impliedTicks: null,
    storedHits: [1],
    marked: false,
    note: 'a toggle. It runs until the mana runs out, so no duration exists to divide and no full-duration total can be stated',
  },
  {
    key: 'Anivia/R/Glacial Storm',
    verdict: 'recurring',
    countVerdict: 'no-duration-stated',
    quote:
      'Anivia calls forth a driving rain of ice and hail at the target location, dealing magic damage every 0.5 seconds to enemies within',
    verbatim: [
      'dealing {{as|magic damage}} every {{fd|0.5}} seconds to enemies within and {{tip|slow|slowing}} them for 1 second',
    ],
    durationSeconds: null,
    intervalSeconds: 0.5,
    impliedTicks: null,
    storedHits: [1, 1],
    marked: false,
    note: 'a toggle, so no duration. Both components — the normal tick and the 300% empowered tick — recur, and the empowered one only begins once the blizzard reaches full size',
  },
  {
    key: 'Aurelion Sol/Q/Breath of Light',
    verdict: 'recurring',
    countVerdict: 'count-not-stored',
    quote:
      'the beam collides with the first enemy hit to burn them, dealing magic damage to them and surrounding enemies every 0.125 seconds',
    verbatim: [
      'dealing {{as|magic damage}} to them and surrounding enemies every {{fd|0.125}} seconds. Secondary targets are dealt 50% damage.',
      '{{tip|channel|charges}} for up to {{fd|3.25}} seconds to exhale a beam of starfire',
    ],
    durationSeconds: 3.25,
    intervalSeconds: 0.125,
    impliedTicks: 26,
    storedHits: [1, 1],
    marked: false,
    note: "THE COUNT IS RANK-DEPENDENT and cannot be one number: the source's own total row is labelled 'Ranks 1-4' and uses 26 ticks, while at rank 5 the channel duration is increased to 160 seconds. A single `hits` value would be wrong at one rank or the other",
  },
  {
    key: 'Aurelion Sol/E/Singularity',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Aurelion Sol conjures a black hole at the target location that lasts for 5 seconds, dealing magic damage every 0.25 seconds to enemies within',
    verbatim: [
      'that lasts for 5 seconds, granting {{tip|sight}} of the area and dealing {{as|magic damage}} every {{fd|0.25}} seconds to enemies within',
    ],
    durationSeconds: 5,
    intervalSeconds: 0.25,
    impliedTicks: 20,
    storedHits: [20],
    marked: true,
  },
  {
    key: 'Cassiopeia/Q/Noxious Blast',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'enemies within the blast are poisoned for 3 seconds, taking magic damage every 3/7 seconds over the duration',
    verbatim: [
      'are {{tip|poison|poisoned}} for 3 seconds, taking {{as|magic damage}} every {{ap|3/7|round=3}} seconds over the duration',
      'damage / 7 ticks rounded down to the nearest integer',
    ],
    durationSeconds: 3,
    intervalSeconds: 3 / 7,
    impliedTicks: 7,
    storedHits: [7],
    marked: true,
    note: "the page states the tick count twice — the interval implies 7 and the notes say '7 ticks' outright",
  },
  {
    key: 'Corki/W/Valkyrie',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'each blazing patch lasts 2.5 seconds, and enemies within the patches are dealt magic damage every 0.5 seconds',
    verbatim: [
      'Each patch lasts {{fd|2.5}} seconds.',
      'Enemies within the patches are dealt {{as|magic damage}} every {{fd|0.5}} seconds, lingering for 1 second.',
    ],
    durationSeconds: 2.5,
    intervalSeconds: 0.5,
    impliedTicks: 5,
    storedHits: [5],
    marked: true,
    note: "5 ticks is ONE patch. The dash drops up to 3 patches, but a target standing in one takes one patch's worth; the source gives no count for overlapping patches",
  },
  {
    key: 'Corki/E/Gatling Gun',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Corki sprays bullets in a cone toward his facing direction for 4 seconds, dealing physical damage every 0.25 seconds to all enemies hit',
    verbatim: [
      'sprays bullets in a cone toward his facing direction for 4 seconds, dealing {{as|physical damage}} every {{fd|0.25}} seconds to all enemies hit',
    ],
    durationSeconds: 4,
    intervalSeconds: 0.25,
    impliedTicks: 16,
    storedHits: [16],
    marked: true,
  },
  {
    key: 'Dr. Mundo/W/Heart Zapper',
    verdict: 'recurring',
    countVerdict: 'settled',
    quote:
      'Dr. Mundo charges up a defibrillator for up to 3 seconds, dealing magic damage every 0.25 seconds to nearby enemies',
    verbatim: [
      'charges up a defibrillator for up to 3 seconds, dealing {{as|magic damage}} every {{fd|0.25}} seconds to nearby enemies',
      '{{st|Magic Damage per Tick|{{ap|5 to 20}}|Total Magic Damage|{{ap|5*16 to 20*16}}}}',
    ],
    durationSeconds: 3,
    intervalSeconds: 0.25,
    impliedTicks: 12,
    storedHits: [16],
    statedTotal: {
      instances: 12,
      componentIds: ['magic-damage-per-tick'],
      statedBy:
        'the description states the duration and the interval — up to 3 seconds, every 0.25 ' +
        'seconds — which is 12 instances. Its own leveling row multiplies by 16, and 16 is the ' +
        'stale figure: it was right while the duration was 4 seconds',
      settledBy:
        "Riot's patch notes for V12.23 on leagueoflegends.com, which reduced Heart Zapper's " +
        'duration from 4 seconds to 3 and were never carried into the leveling row. The wiki\'s ' +
        "own patch history records the same change, and Riot's live tooltip string computes the " +
        'damage as damage-per-second times 3',
      verbatim:
        'charges up a defibrillator for up to 3 seconds, dealing {{as|magic damage}} every {{fd|0.25}} seconds to nearby enemies',
    },
    marked: true,
    note: "SETTLED 2026-08-15 (DATA-SOURCES §59.2) at 12, not the stored 16: the row overstates by 33%. TWO CAVEATS TRAVEL WITH THE 12 and neither is modelled. The description says 'up TO 3 seconds' and the ability can be recast early, so 12 is a MAXIMUM rather than a fixed count — the engine models sequence, not elapsed time, so it publishes the full-duration figure as every other marked burn does. And the page's own notes record that it 'will occasionally deal an additional tick of damage' as a bug, which would make the real figure 13 and which nothing here reproduces. THE ENTRY IS `incomplete` IN THE HARVEST AND STAYS THERE, so this correction publishes no number today; it stops a wrong one being published if it ever ceases to be incomplete",
  },
  {
    key: 'Fiddlesticks/R/Crowstorm',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'a murder of crows flies wildly around the target location for 5 seconds, dealing magic damage every 0.25 seconds to nearby enemies',
    verbatim: [
      'with a murder of crows flying wildly around it for 5 seconds, dealing {{as|magic damage}} every {{fd|0.25}} seconds to nearby enemies',
    ],
    durationSeconds: 5,
    intervalSeconds: 0.25,
    impliedTicks: 20,
    storedHits: [20],
    marked: true,
  },
  {
    key: 'Hecarim/W/Spirit of Dread',
    verdict: 'recurring',
    countVerdict: 'settled',
    quote:
      'Hecarim surrounds himself with the Spirit of Dread for 4 seconds, dealing magic damage every second to nearby enemies',
    verbatim: [
      'surrounds himself with the Spirit of Dread for 4 seconds, dealing {{as|magic damage}} every second to nearby enemies',
      '{{st|Magic Damage Per Tick|{{ap|20 to 60}} {{as|(+ 20% AP)}}|Total Magic Damage|{{ap|20*5 to 60*5}}',
    ],
    durationSeconds: 4,
    intervalSeconds: 1,
    impliedTicks: 4,
    storedHits: [5],
    statedTotal: {
      instances: 4,
      componentIds: ['magic-damage-per-tick'],
      statedBy:
        'the description states the duration and the interval — 4 seconds, every second — which ' +
        'is 4 instances. Its own leveling row multiplies by 5, and 5 is the stale figure: it was ' +
        'right while the duration was 5 seconds',
      settledBy:
        "Riot's patch notes for V14.14 on leagueoflegends.com, which state \"Duration: 5 ⇒ 4 " +
        'seconds\" — confirmed outside the wiki entirely. The game data matches the description ' +
        'at all five ranks and on the AP ratio; the editor updated the sentence in July 2024 and ' +
        'left the multiplier',
      verbatim:
        'surrounds himself with the Spirit of Dread for 4 seconds, dealing {{as|magic damage}} every second to nearby enemies',
    },
    marked: true,
    note: "SETTLED 2026-08-15 (DATA-SOURCES §59.1) at 4, not the stored 5: the row overstates by 25%. THIS IS THE ONE ROW IN THIS TABLE THAT PUBLISHES A NUMBER — the harvest holds Hecarim W as `derived`, so marking it puts 4 x (20 to 60) (+ 4 x 20% AP) on the damage-over-time line where 5 x would have gone into burst. WHAT THE 4 IS AND IS NOT: DATA-SOURCES §59.1 records that the real tick interval is 0.5s, so the true number of damage INSTANCES is 8 — the wiki's 'Per Tick' label is really per-second. 4 is therefore the right multiplier for the STATED FIGURE and NOT the number of instances, and the full-duration product is the same either way. (§59.1 also says each instance deals 'a fifth' of the stated figure; 8 instances summing to 4 x the stated figure makes each a HALF. The discrepancy is raised rather than resolved here, and it does not affect the product, which is all the engine uses)",
  },
  {
    key: 'Hwei/Q/Molten Fissure',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'a fissure lasts for 2.5 seconds, dealing magic damage every 0.25 seconds to enemies within the area',
    verbatim: [
      'A fissure lasts for {{fd|2.5}} seconds, dealing {{as|magic damage}} every {{fd|0.25}} seconds to enemies within the area',
    ],
    durationSeconds: 2.5,
    intervalSeconds: 0.25,
    impliedTicks: 10,
    storedHits: [10],
    marked: true,
    note: "10 ticks is ONE fissure, which is the conservative reading. The page adds that 'Enemies may be damaged by multiple fissures at once' but gives no count for how many overlap",
  },
  {
    key: 'Hwei/R/Spiraling Despair',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'the target is afflicted with an aura that grows over 3 seconds, and enemies within are dealt magic damage every 0.25 seconds',
    verbatim: [
      'afflicting them with an [[aura]] that grows over 3 seconds',
      "Enemies within are both dealt {{as|magic damage}} and applied a {{tip|stack}} of ''Despair'' every {{fd|0.25}} seconds.",
    ],
    durationSeconds: 3,
    intervalSeconds: 0.25,
    impliedTicks: 12,
    storedHits: [12],
    marked: true,
    note: 'the detonation at the end of the duration is a separate component and stays in the burst line',
  },
  {
    key: 'Jayce/W/Lightning Field',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Jayce surrounds himself with an electric field for 4 seconds that deals magic damage every second to nearby enemies',
    verbatim: [
      'surrounds himself with an electric field for 4 seconds that deals {{as|magic damage}} every second to nearby enemies',
    ],
    durationSeconds: 4,
    intervalSeconds: 1,
    impliedTicks: 4,
    storedHits: [4],
    marked: true,
  },
  {
    key: 'Karthus/E/Defile',
    verdict: 'recurring',
    countVerdict: 'no-duration-stated',
    quote:
      'Karthus surrounds himself in a necrotic aura that deals magic damage every 0.25 seconds to all nearby enemies',
    verbatim: [
      'surrounds himself in a necrotic [[aura]] that deals {{as|magic damage}} every {{fd|0.25}} seconds to all nearby enemies',
    ],
    durationSeconds: null,
    intervalSeconds: 0.25,
    impliedTicks: null,
    storedHits: [1],
    marked: false,
    note: 'a toggle held up by mana. The source gives a per-second figure and no duration, so there is no full-duration total to state',
  },
  {
    key: 'Malzahar/E/Malefic Visions',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      "Malzahar infects the target enemy's mind, dealing magic damage every 0.25 seconds over 4 seconds",
    verbatim: [
      "infects the target enemy's mind, dealing {{as|magic damage}} every {{fd|0.25}} seconds over 4 seconds",
    ],
    durationSeconds: 4,
    intervalSeconds: 0.25,
    impliedTicks: 16,
    storedHits: [16],
    marked: true,
    note: 'the duration refreshes on a further hit, so 16 is the count for one uninterrupted application — which is what the source states',
  },
  {
    key: 'Malzahar/R/Nether Grasp',
    verdict: 'recurring',
    countVerdict: 'count-not-stored',
    quote:
      'Malzahar channels for up to 2.5 seconds, dealing the target magic damage every 0.25 seconds, and a Null Zone lasting 5 seconds deals magic damage every 0.5 seconds to enemies within',
    verbatim: [
      'dealing them {{as|magic damage}} every {{fd|0.25}} seconds, {{tip|sight|revealing}} himself in the process',
      'that lasts 5 seconds, dealing {{as|magic damage}} every {{fd|0.5}} seconds to enemies within',
      '{{st|Total Magic Damage|{{ap|125 to 275}} {{as|(+ 80% AP)}}|Magic Damage Per Tick|{{ap|125/10 to 275/10}} {{as|(+ 8% AP)}}}}',
      "|Magic Damage Per Tick|{{as|{{ap|10/10 to 20/10}}% {{as|(+ {{fd|0.25}}% per 100 AP)}} of target's '''maximum''' health}}",
    ],
    durationSeconds: 2.5,
    intervalSeconds: 0.25,
    impliedTicks: 10,
    storedHits: [1, 1],
    reconcilesAt: 10,
    captureBlockedBy:
      "a defect in our own harvest, not a gap in the source: this entry's two per-tick rows are " +
      "stored under one component id ('magic-damage-per-tick'), so a captured count names two " +
      'rows at once and can be attached to neither. Gate 1 rejects the entry for the same reason ' +
      'and it is refused from the merged file entirely. It becomes capturable the moment the ' +
      'harvester gives each row a distinct id and a fresh full-roster run lands.',
    marked: false,
    note: 'RE-READ 2026-08-15. BOTH halves state 10 and the page prints it for both: the tether is 2.5s / 0.25s and its own Total row divides by 10 on the base and on the AP ratio, and the Null Zone is 5s / 0.5s with its own Total row dividing by 10 the same way. So the source is not short of anything — our storage is. Both components hold 1',
  },
  {
    key: 'Mel/E/Solar Snare',
    verdict: 'recurring',
    countVerdict: 'no-duration-stated',
    quote:
      'enemies within the field are dealt magic damage and slowed by 30% every 0.125 seconds, lingering for 0.25 seconds after exiting',
    verbatim: [
      'Enemies within the field are dealt {{as|magic damage}} and {{tip|slow|slowed}} by 30% every {{fd|0.125}} seconds, lingering for {{fd|0.25}} seconds after exiting.',
    ],
    durationSeconds: null,
    intervalSeconds: 0.125,
    impliedTicks: null,
    storedHits: [1],
    marked: false,
    note: "the field's own lifetime is never stated — the source gives a per-second figure (8 ticks) and the orb's 1.5-second root, neither of which is a field duration. Also refused from the merged file for two same-label rows",
  },
  {
    key: 'Miss Fortune/E/Make It Rain',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Miss Fortune casts a storm of bullets at the target location for 2 seconds, dealing magic damage every 0.25 seconds to enemies within',
    verbatim: [
      'casts a storm of bullets at the target location for 2 seconds, granting {{tip|sight}} of the area, dealing {{as|magic damage}} every {{fd|0.25}} seconds to enemies within',
    ],
    durationSeconds: 2,
    intervalSeconds: 0.25,
    impliedTicks: 8,
    storedHits: [8],
    marked: true,
  },
  {
    key: 'Morgana/W/Tormented Shadow',
    verdict: 'recurring',
    // RE-READ 2026-08-15 AND MOVED FROM 'count-not-stored' TO 'contested'. The count is not
    // missing from the source — the source states TWO of them. Its description reads as 11
    // instances (one on cast, then one every 0.5s across a 5-second field) and its own total row
    // multiplies the per-tick figure by 10. Neither is taken silently (DATA-SOURCES §32.2), and
    // no evidence outside the page settles which the game does, so nothing is captured here.
    countVerdict: 'contested',
    quote:
      'the area becomes desecrated for 5 seconds, and enemies within take magic damage on-cast and every 0.5 seconds thereafter, while the page own total row multiplies the per-tick figure by 10',
    verbatim: [
      'causing the area to become desecrated for 5 seconds. Enemies within take {{as|magic damage}} on-cast and every {{fd|0.5}} seconds thereafter',
      '{{st|Minimum Total Damage|{{ap|9*10 to 35*10}}',
    ],
    durationSeconds: 5,
    intervalSeconds: 0.5,
    impliedTicks: 10,
    storedHits: [1, 1],
    marked: false,
    note: "'on-cast AND every 0.5 seconds thereafter' reads as 11 instances while the source's own total row multiplies by 10, and one extra instance is 10% of the ability. Both components store 1. A second question sits behind it and is NOT fixed by a count: the minimum and maximum per-tick rows are the two ends of one missing-health scaling, and the harvest now stores the maximum as an alternative to the minimum, so capturing a count would still leave the entry unable to state its own total",
  },
  {
    key: 'Naafiri/Q/Darkin Daggers',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'the dagger inflicts a bleed that deals bonus physical damage every 0.5 seconds over 5 seconds',
    verbatim: [
      "inflicts them with a {{as|bleed|buzzword3}} that deals {{as|'''bonus''' physical damage}} every {{fd|0.5}} seconds over 5 seconds",
    ],
    durationSeconds: 5,
    intervalSeconds: 0.5,
    impliedTicks: 10,
    storedHits: [10],
    marked: true,
    note: 'the initial dagger hit is a separate component and stays in the burst line',
  },
  {
    key: 'Nasus/E/Spirit Fire',
    verdict: 'recurring',
    countVerdict: 'contested',
    quote:
      'the fire remains for 5 seconds, dealing magic damage each second to enemies within and inflicting armor reduction',
    verbatim: [
      'The fire then remains for 5 seconds, dealing {{as|magic damage}} each second to enemies within',
      '{{st|Magic Damage Per Tick|{{ap|10 to 34}} {{as|(+ 12% AP)}}|Total Magic Damage|{{ap|10*10 to 34*10}}',
    ],
    durationSeconds: 5,
    intervalSeconds: 1,
    impliedTicks: 5,
    storedHits: [10],
    marked: false,
    note: "THE SOURCE DISAGREES WITH ITSELF BY A FACTOR OF TWO: the description says each second for 5 seconds, which is 5 ticks; its own total row multiplies the per-tick figure by 10. INVESTIGATED AND STILL REFUSED 2026-08-15 (DATA-SOURCES §59.3). The TOTAL is settled — Riot's V14.18 patch notes state the figure verbatim as 'Damage per Second' and the game multiplies it by the duration, so the product is 50-170 (+60% AP) over 5 seconds and the row's x10 doubles it. But NO SOURCE STATES THE INTERVAL: the wiki's damage-over-time article gives none, the game data carries no tick rate, and the buff object is an empty stub, so '5 ticks of 10-34' and '10 ticks of 5-17' are both consistent with everything reachable. A count cannot be computed from a duration alone. This row stays `contested` and unmarked BY DECISION, not by omission — settling it needs a frame-counted in-client observation or a spell script nobody publishes",
  },
  {
    key: 'Nasus/R/Fury of the Sands',
    verdict: 'recurring',
    countVerdict: 'captured',
    quote:
      'Nasus empowers himself for 15 seconds, and while empowered he deals magic damage every 0.5 seconds to nearby enemies',
    verbatim: [
      'empowers himself for 15 seconds',
      'he deals {{as|magic damage}} every {{fd|0.5}} seconds to nearby enemies, capped at 240 per second',
      "|Total Magic Damage|{{as|{{ap|1.5*30 to 2.5*30}}% {{as|(+ {{ap|0.5*30}}% per 100 AP)}} of target's '''maximum''' health}}",
    ],
    durationSeconds: 15,
    intervalSeconds: 0.5,
    impliedTicks: 30,
    storedHits: [1],
    statedTotal: {
      instances: 30,
      componentIds: ['magic-damage-per-tick'],
      statedBy:
        'the description states the duration and the interval — 15 seconds, every 0.5 seconds — ' +
        "which is 30 instances, and the page's own Total row writes the multiplier out twice: " +
        "'1.5*30 to 2.5*30' on the health percentage and '0.5*30' on the per-100-AP term, so the " +
        'count of 30 is printed at every rank and on the coefficient as well',
      verbatim:
        "|Total Magic Damage|{{as|{{ap|1.5*30 to 2.5*30}}% {{as|(+ {{ap|0.5*30}}% per 100 AP)}} of target's '''maximum''' health}}",
    },
    marked: true,
    note: "CAPTURED 2026-08-15: three statements agree on 30 — 15s / 0.5s, the Total row's own '*30' on the base, and the same '*30' on the AP coefficient. A FOURTH agreement is worth recording because it is not from this page at all: Renekton R is the same shape to the second — a 15-second self-empowerment aura ticking every 0.5 seconds — and this project already reads it at 30, corroborated. THE ENTRY STAYS `incomplete` IN THE HARVEST and publishes nothing today; the capture stops a thirtieth of the burn being published as the whole of it if it ever ceases to be. NOT MODELLED and stated rather than hidden: the source caps the aura at 240 damage per second, which binds only against a target above roughly 8,000 maximum health at rank 1, and nothing in the contract can express a per-second cap on a sequence engine",
  },
  {
    key: 'Nidalee/W/Bushwhack',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'the trap springs upon contact with an enemy, dealing magic damage every second over 4 seconds',
    verbatim: [
      'The trap will spring upon contact with an enemy, dealing {{as|magic damage}} every second over 4 seconds.',
    ],
    durationSeconds: 4,
    intervalSeconds: 1,
    impliedTicks: 4,
    storedHits: [4],
    marked: true,
  },
  {
    key: 'Nocturne/E/Unspeakable Horror',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Nocturne forms a tether between himself and the target for 2 seconds, during which the target takes magic damage every 0.5 seconds over the duration',
    verbatim: [
      'forming a {{tip|tether}} between himself and the target for 2 seconds, during which the target takes {{as|magic damage}} every {{fd|0.5}} seconds over the duration',
    ],
    durationSeconds: 2,
    intervalSeconds: 0.5,
    impliedTicks: 4,
    storedHits: [4],
    marked: true,
  },
  {
    key: 'Ornn/W/Bellows Breath',
    verdict: 'recurring',
    countVerdict: 'count-not-stored',
    quote:
      'over the 0.75-second march Ornn belches fire over a cone in front of him, dealing magic damage every 0.15 seconds to enemies hit',
    verbatim: [
      '{{tip|lunge|marches}} forward in the target direction over {{fd|0.75}} seconds',
      'he belches fire over a cone in front of him, dealing {{as|magic damage}} every {{fd|0.15}} seconds to enemies hit',
    ],
    durationSeconds: 0.75,
    intervalSeconds: 0.15,
    impliedTicks: 5,
    storedHits: [1],
    reconcilesAt: 5,
    captureBlockedBy:
      'not the count — the DESTINATION. Capturing a count marks the component as recurring, ' +
      'which moves its whole figure out of the burst total and into the damage-over-time line, ' +
      'and SPECIFICATION §3.8 defines that line as damage "delivered over the effect\'s full ' +
      'duration FOLLOWING the combo". All five gouts land inside the 0.75-second lunge itself, ' +
      'so nothing follows the combo at all. Marking it would show 0 burst damage for an ability ' +
      'that resolves inside one cast. RAISED for the lead rather than decided here.',
    marked: false,
    note: "RE-READ 2026-08-15. THE COUNT IS NOT THE PROBLEM AND THIS ROW USED TO IMPLY IT WAS. Three statements agree on 5 — 0.75s / 0.15s, and the page divides its total by 5 in three separate rows (champion damage 12/5 to 16/5, minion 80/5 to 280/5, monster cap 260/5 to 500/5). What is unresolved is where the figure belongs: five gouts inside a single 0.75-second lunge is a sweep, this is the ONLY member of this population the wiki tags 'aoe' rather than 'aoedot', and §3.8's damage-over-time line is defined as damage following the combo. The shortest marked burn is Yunara W at 1 second, so 0.75 seconds is not far outside it and the question is genuinely close — which is why it is raised rather than settled by preference",
  },
  {
    key: 'Rell/R/Magnet Storm',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Rell creates a gravitational field around her for the next 2 seconds that deals magic damage every 0.25 seconds to nearby enemies',
    verbatim: [
      'creating a gravitational field around her for the next 2 seconds that deals {{as|magic damage}} every {{fd|0.25}} seconds to nearby enemies',
    ],
    durationSeconds: 2,
    intervalSeconds: 0.25,
    impliedTicks: 8,
    storedHits: [8],
    marked: true,
  },
  {
    key: 'Renekton/R/Dominus',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Renekton empowers himself for 15 seconds, and during this time he deals magic damage every 0.5 seconds to nearby enemies',
    verbatim: [
      "'''Renekton''' empowers himself for 15 seconds",
      'he deals {{as|magic damage}} every {{fd|0.5}} seconds to nearby enemies and generates {{as|5 Fury}} per second',
    ],
    durationSeconds: 15,
    intervalSeconds: 0.5,
    impliedTicks: 30,
    storedHits: [30],
    marked: true,
    note: 'all 30 ticks were publishing as BURST damage before the withdrawal, which is the single largest figure this reading moves',
  },
  {
    key: 'Rumble/Q/Flamespitter',
    verdict: 'recurring',
    countVerdict: 'count-not-stored',
    quote:
      'Rumble activates his flamethrower for 3 seconds, spewing forth flames in a frontal cone every 0.25 seconds, and enemies hit are scorched, taking magic damage every 0.25 seconds',
    verbatim: [
      'activate his flamethrower for 3 seconds, spewing forth flames in a {{tt|frontal|In his facing direction}} cone every {{fd|0.25}} seconds',
      'Values are defined OVER 3 SECONDS',
      "Enemies hit by the flame are scorched for {{ap|0.5<!-- Primary debuff duration (2 instances) --> + 0.1<!-- Offset -->}} seconds, taking {{as|magic damage}} every {{fd|0.25}} seconds as well as upon being hit if not currently scorched",
      '{{st|Minimum Magic Damage|{{ap|({{#var:q_b1}}/12)*3 to ({{#var:q_b5}}/12)*3|round=2}}',
      '|Maximum Magic Damage|{{ap|{{#var:q_b1}}*(15/12) to {{#var:q_b5}}*(15/12)|round=2}}',
    ],
    durationSeconds: 3,
    intervalSeconds: 0.25,
    impliedTicks: 12,
    storedHits: [1, 1],
    marked: false,
    note: "RE-READ 2026-08-15, AND THE PAGE TURNS OUT TO BE ENTIRELY SELF-CONSISTENT — WHICH IS WHY NO COUNT CAN BE CAPTURED. It states THREE counts for three different situations and every one of them reconciles: 3 for a target clipped once (a 0.5-second scorch ticks twice, plus one instance on application, which is the note this page shares with Singed Q), 12 for the flamethrower's own 3 seconds at 0.25-second intervals, and 15 as the maximum — twelve emissions, two trailing ticks after the last refresh, and the application instance. The capture rule requires the corrected count to EQUAL the source's duration over its interval, and the full-duration figure here is 15 against an arithmetic of 12, so the rule refuses it and is right to: which number applies is a property of how long the target stands in the cone, not of the ability. Both the normal and the Danger Zone component store 1",
  },
  {
    key: 'Rumble/R/The Equalizer',
    verdict: 'recurring',
    countVerdict: 'captured',
    quote:
      'enemies struck by the impact or within the field are marked Burning for 1 second, taking magic damage every 0.25 seconds, and may be Burning for up to 5 seconds, for a total of 20 instances of its effect',
    verbatim: [
      "are marked ''Burning'' for 1 second, taking {{as|magic damage}} every {{fd|0.25}} seconds",
      "Enemies may be ''Burning'' for up to 5 seconds, for a total of 20 instances of its effect.",
      '{{st|Magic Damage per Tick|{{ap|{{#var:r_b1}}/4 to {{#var:r_b5}}/4}}',
      '|Maximum Magic Damage|{{ap|{{#var:r_b1}}*5 to {{#var:r_b5}}*5}}',
    ],
    durationSeconds: 5,
    intervalSeconds: 0.25,
    impliedTicks: 20,
    storedHits: [1],
    statedTotal: {
      instances: 20,
      componentIds: ['magic-damage-per-tick'],
      statedBy:
        'the description states it in words — "for a total of 20 instances of its effect" — and ' +
        "the page's own leveling row states it a second way: the per-tick figure is the " +
        'per-second figure divided by 4, and the Maximum row is the per-second figure times 5, ' +
        'so the maximum is the per-tick figure times 20 at every rank and on the AP ratio too',
      verbatim:
        "Enemies may be ''Burning'' for up to 5 seconds, for a total of 20 instances of its effect.",
    },
    marked: true,
    note: "CAPTURED 2026-08-15: three statements agree on 20 — the sentence's own words, 5s / 0.25s, and the leveling row's own multiplier (base/4 per tick against base*5 maximum). THE ENTRY STAYS `incomplete` REGARDLESS, and not for the count: its three components — per tick, per second, and Maximum — are three expressions of ONE damage and the harvest marked all three 'adds', so summing them would treble it. That is a separate defect and it is not fixed here",
  },
  {
    key: 'Singed/Q/Poison Trail',
    verdict: 'recurring',
    // RE-READ 2026-08-15 AND MOVED FROM 'count-not-stored' TO 'contested'. The page states two
    // counts for one application, not one: its own Minimum row multiplies by 8, while its
    // description and its notes together describe 9 — eight ticks over the two-second poison plus
    // one instance dealt at the moment of application. Neither is taken silently (§32.2).
    countVerdict: 'contested',
    quote:
      'the poisoned target takes magic damage every 0.25 seconds over 2 seconds as well as upon being hit if not currently affected, and the page own notes add that a fresh application deals one additional instance at the same time, while its own minimum row multiplies the per-tick figure by 8',
    verbatim: [
      'The target takes {{as|magic damage}} every {{fd|0.25}} seconds over 2 seconds as well as upon being hit if not currently affected.',
      "When ''Poison Trail's'' debuff is applied instead of refreshed, the target is dealt one additional instance of the debuff at the same time as the application.",
      '|Minimum Magic Damage|{{ap|({{#var:q_b1}}/4)*8 to ({{#var:q_b5}}/4)*8}}',
    ],
    durationSeconds: 2,
    intervalSeconds: 0.25,
    impliedTicks: 8,
    storedHits: [1],
    marked: false,
    note: "THE PAGE STATES TWO COUNTS FOR ONE FRESH APPLICATION AND NOTHING SETTLES WHICH. Its Minimum row multiplies the per-tick figure by 8, which is 2 seconds / 0.25 seconds exactly. Its description says the poison lands 'as well as upon being hit if not currently affected', and its notes say so in the arithmetic's own words — 'the target is dealt one additional instance of the debuff at the same time as the application' — which is 9. The difference is 12.5% of the ability. THE PAGE IS INTERNALLY CONSISTENT ABOUT THE SAME RULE ELSEWHERE, which is what makes this a contradiction rather than a nuance: Rumble Q carries the identical note and ITS minimum row does count the application instance, multiplying by 3 for a 0.5-second debuff that ticks twice. Nothing outside the page settles Singed's, so neither 8 nor 9 is adopted. A separate fact travels with it and no count fixes it: the cloud refreshes the poison while Singed keeps walking, so any single number is a floor",
  },
  {
    key: 'Swain/R/Demonic Ascension',
    verdict: 'recurring',
    countVerdict: 'no-duration-stated',
    quote:
      'Swain drains the lifeforce of nearby enemies, both dealing magic damage and healing himself every 0.5 seconds per target affected',
    verbatim: [
      'drains the lifeforce of nearby enemies, both dealing {{as|magic damage}} and {{tip|healing}} himself every {{fd|0.5}} seconds per target affected',
      'which decays by {{as|5|azakana}} every {{fd|0.5}} seconds, increased to {{as|{{fd|7.5}}|azakana}} after 5 seconds have elapsed',
    ],
    durationSeconds: null,
    intervalSeconds: 0.5,
    impliedTicks: null,
    storedHits: [1],
    marked: false,
    note: "RE-READ 2026-08-15 AND STILL REFUSED, now with the arithmetic that was tempting stated rather than left implicit. The source gives no duration; it gives a resource. Demonic Energy starts at 50 and decays by 5 every 0.5 seconds, which empties it in exactly 5 seconds and looks like a 10-tick answer. It is not one: the same sentence says Swain GENERATES 10 every 0.5 seconds while draining a champion, a net gain, so the ability runs indefinitely in the situation it is cast in, and a takedown refills it to full. The 5-second figure is the duration of a cast that hits nothing, which is the one case where the count does not matter. NO DURATION IS INFERRED FROM A DECAY RATE",
  },
  {
    key: 'Udyr/R/Wingborne Storm',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Udyr summons a blizzard around himself for 4 seconds that deals magic damage every 0.5 seconds to nearby enemies',
    verbatim: [
      'summons a blizzard around himself for 4 seconds that deals {{as|magic damage}} every {{fd|0.5}} seconds to nearby enemies',
    ],
    durationSeconds: 4,
    intervalSeconds: 0.5,
    impliedTicks: 8,
    storedHits: [8],
    marked: true,
    note: "the Awakened recast's maximum-health bonus is stated per tick as well, and is not part of this component",
  },
  {
    key: 'Viktor/R/Arcane Storm',
    verdict: 'recurring',
    countVerdict: 'captured',
    quote:
      'the singularity remains active as a moving storm for 6.5 seconds, striking a bolt of electricity onto enemies within it every second to deal magic damage',
    verbatim: [
      'The singularity then remains active as a moving storm for {{fd|6.5}} seconds, striking a bolt of electricity onto enemies within it every second to deal {{as|magic damage}}',
      'The base duration allows for 7 strikes (including the initial one).',
      '|Total Magic Damage|{{ap|100+65*6 to 250+145*6}} {{as|(+ {{ap|50+35*6}}% AP)}}',
    ],
    durationSeconds: 6.5,
    intervalSeconds: 1,
    impliedTicks: 6,
    storedHits: [1],
    statedTotal: {
      instances: 6,
      componentIds: ['magic-damage-per-tick'],
      statedBy:
        'the page states "7 strikes (including the initial one)" and the initial strike is a ' +
        'separate component, leaving 6 for the storm — and its own Total row writes the ' +
        'multiplier out, "100+65*6 to 250+145*6", with the AP ratio as "50+35*6", so the count ' +
        'of 6 is printed by the source at every rank and on the ratio',
      verbatim: 'The base duration allows for 7 strikes (including the initial one).',
    },
    marked: true,
    note: "CAPTURED 2026-08-15: three statements agree on 6 — the note's 7 strikes less the initial one, 6.5s / 1s, and the Total row's own '*6'. The capture also RECONCILES the arithmetic behind this entry's gate-7 failure, which was the harvest reporting a total of 490 against components summing to 165: 100 + 65 x 6 = 490 exactly. IT DOES NOT CLEAR THE GATE-7 REPORT: gate 7 is answered during harvest and merge-proposal.ts carries the finding rather than recomputing it, so the entry keeps its total-mismatch issue and its `incomplete` status until a fresh harvest runs. Nothing is published either way",
  },
  {
    key: 'Vladimir/W/Sanguine Pool',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'Vladimir sinks into a pool of blood for 2 seconds, and enemies within the pool are dealt magic damage every 0.5 seconds over the duration',
    verbatim: [
      'becoming {{tip|untargetable}} and {{tip|ghosted}} for 2 seconds',
      'Enemies within the pool are dealt {{as|magic damage}} every {{fd|0.5}} seconds over the duration',
    ],
    durationSeconds: 2,
    intervalSeconds: 0.5,
    impliedTicks: 4,
    storedHits: [4],
    marked: true,
    note: "the page's notes confirm the shape: the first tick damages immediately so the final one occurs 0.5 seconds before Vladimir becomes targetable again",
  },
  {
    key: 'Wukong/R/Cyclone',
    verdict: 'recurring',
    countVerdict: 'captured',
    quote:
      'Wukong spins his staff around for up to 2 seconds, and the staff deals physical damage every 0.25 seconds to enemies hit',
    verbatim: [
      'spins his staff around for up to 2 seconds',
      'The staff deals {{as|physical damage}} every {{fd|0.25}} seconds to enemies hit',
      "|Total Physical Damage|{{as|{{ap|8 to 16}}% of target's '''maximum''' health}} {{as|(+ 275% AD)}}",
    ],
    durationSeconds: 2,
    intervalSeconds: 0.25,
    impliedTicks: 8,
    storedHits: [1],
    statedTotal: {
      instances: 8,
      componentIds: ['physical-damage-per-tick'],
      statedBy:
        'the description states the duration and the interval — up to 2 seconds, every 0.25 ' +
        "seconds — which is 8 instances, and the page's own leveling row divides the total by 8 " +
        "on both terms: '8/8 to 16/8' of the health percentage against a total of '8 to 16', and " +
        "'275/8' of the AD ratio against a total of 275",
      verbatim:
        "|Total Physical Damage|{{as|{{ap|8 to 16}}% of target's '''maximum''' health}} {{as|(+ 275% AD)}}",
    },
    marked: true,
    note: "CAPTURED 2026-08-15: three statements agree on 8 — 2s / 0.25s, the leveling row's '/8' on the health percentage, and the same '/8' on the AD ratio. THE 2-SECOND SPIN QUESTION IS NOT REOPENED BY THIS and is not decided by it either: the count is what is captured. Two entries already marked recur over exactly 2 seconds — Nocturne E and Vladimir W — and the wiki tags this ability 'aoedot' as it tags them, so nothing here is a new reading of the destination. CAVEATS, none modelled: 'up to 2 seconds' means the spin can be interrupted, so 8 is a maximum; the recast doubles the total, which the page states as a separate Maximum row and is not stored; and the per-second cap against monsters is out of scope for champion damage. THE ENTRY STAYS `incomplete` in the harvest and publishes nothing today",
  },
  {
    key: 'Yunara/W/Arc of Judgment',
    verdict: 'recurring',
    countVerdict: 'corroborated',
    quote:
      'upon reaching maximum range the bead expands and lingers in place for 1 second, and while lingering it deals a share of the impact damage as magic damage to nearby enemies every 0.25 seconds',
    verbatim: [
      'it will expand and linger in place for 1 second regardless of enemies hit',
      'the bead deals {{#expr:{{#var:lm}}*100/4}}% of the impact damage as {{as|magic damage}} to nearby enemies every {{fd|0.25}} seconds',
    ],
    durationSeconds: 1,
    intervalSeconds: 0.25,
    impliedTicks: 4,
    storedHits: [4],
    marked: true,
    note: "the 1-second linger is the only duration the source fixes; the in-flight linger resets its remaining duration and has no stated length, so 4 is the count for the expanded bead",
  },
];

/** The entries this reading marks as recurring, as `key -> the sentence it rests on`. */
export function markedOverTime(): ReadonlyMap<string, string> {
  return new Map(PER_TICK_READS.filter((r) => r.marked).map((r) => [r.key, r.quote]));
}

/** The three count verdicts a row may be marked on. Every other verdict leaves it withdrawn. */
export const MARKABLE_COUNT_VERDICTS: readonly CountVerdict[] = ['corroborated', 'captured', 'settled'];

/** The two verdicts that CORRECT a stored hit count rather than agreeing with it. */
export const CORRECTING_COUNT_VERDICTS: readonly CountVerdict[] = ['captured', 'settled'];

/**
 * A MARKED ROW MUST BE RECURRING AND ITS COUNT ESTABLISHED. Nothing else may be marked.
 *
 * The rule the table is written to, restated as a check so a later edit cannot quietly break it:
 * marking a row whose count is contested or unstored publishes a wrong burn total. There are
 * exactly three ways a count can be established, and every one of them ends at the same
 * arithmetic — the source's own duration divided by its own interval:
 *
 *   - `corroborated` — the harvest already holds that number.
 *   - `captured`     — the harvest holds 1 and the page PRINTS the number in words or in its own
 *                      total-row multiplier.
 *   - `settled`      — the page contradicts itself and evidence from outside the page decided it.
 *
 * A row that reaches the number any other way is not markable, and Nasus E is the standing proof:
 * its total is settled and its interval is stated by nothing, so no count exists to check.
 */
export function checkMarkRule(reads: readonly PerTickRead[] = PER_TICK_READS): string[] {
  const wrong: string[] = [];
  for (const r of reads) {
    const eligible =
      r.verdict === 'recurring' && MARKABLE_COUNT_VERDICTS.includes(r.countVerdict);
    if (r.marked && !eligible) {
      wrong.push(`${r.key}: marked, but it is ${r.verdict} with a ${r.countVerdict} count`);
    }
    if (!r.marked && eligible) {
      wrong.push(`${r.key}: recurring with a ${r.countVerdict} count, but not marked`);
    }
    if (r.marked && !r.quote) wrong.push(`${r.key}: marked with no quote`);
    if (r.countVerdict === 'corroborated' && r.impliedTicks !== r.storedHits[0]) {
      wrong.push(
        `${r.key}: called corroborated, but ${r.durationSeconds}s / ${r.intervalSeconds}s = ` +
          `${r.impliedTicks} and hits is ${r.storedHits[0]}`,
      );
    }
    // A CORRECTING ROW CARRIES MORE CONDITIONS THAN A CORROBORATED ONE, NOT FEWER. Each of these
    // is a way of writing a count nothing checked, which is the defect the whole table exists to
    // prevent — so each is refused by name rather than by a general "looks wrong".
    const corrects = CORRECTING_COUNT_VERDICTS.includes(r.countVerdict);
    if (corrects) {
      const s = r.statedTotal;
      if (!s) {
        wrong.push(`${r.key}: called ${r.countVerdict} but states no corrected count at all`);
      } else {
        if (s.instances !== r.impliedTicks) {
          wrong.push(
            `${r.key}: ${r.countVerdict} ${s.instances} instances, but ${r.durationSeconds}s / ` +
              `${r.intervalSeconds}s = ${r.impliedTicks}. A corrected count must reconcile with ` +
              `the source's own duration and interval, or it is a number nobody checked`,
          );
        }
        if (s.componentIds.length === 0) {
          wrong.push(`${r.key}: ${r.countVerdict} a count and names no component to put it on`);
        }
        if (!s.verbatim || !r.verbatim.includes(s.verbatim)) {
          wrong.push(
            `${r.key}: the corrected count's sentence is not among the row's verbatim fragments, ` +
              `so nothing proves it is in the source`,
          );
        }
        if (r.storedHits.every((h) => h === s.instances)) {
          wrong.push(
            `${r.key}: ${r.countVerdict} ${s.instances}, which the harvest already holds — this ` +
              `row is corroborated, and calling it ${r.countVerdict} hides that nothing changed`,
          );
        }
        // THE ONE CONDITION ONLY A SETTLED ROW CARRIES. A settled row overrides a number the page
        // itself states, so the evidence that overrode it has to be named. Nothing here can check
        // that citation — it is outside the cached page by definition — but an unnamed one is a
        // reader's preference dressed as a source, and that is refusable.
        if (r.countVerdict === 'settled' && !s.settledBy) {
          wrong.push(
            `${r.key}: settled a count the page contradicts, and names no evidence outside the ` +
              `page that settled it`,
          );
        }
        if (r.countVerdict === 'captured' && s.settledBy) {
          wrong.push(
            `${r.key}: called captured — the page prints the count — yet cites outside evidence ` +
              `to settle it. If the page had to be overridden the row is settled, not captured`,
          );
        }
      }
    }
    if (!corrects && r.statedTotal) {
      wrong.push(`${r.key}: carries a corrected count while its verdict is '${r.countVerdict}'`);
    }
    // A RECONCILING COUNT THAT IS NOT WRITTEN MUST SAY WHY IT IS NOT WRITTEN (2026-08-15).
    //
    // The failure guarded against is the quiet one: a row whose count was established, whose
    // blocker was fixed later somewhere else, and which nobody ever came back to. Pairing the
    // number with a stated blocker makes the two move together — remove the blocker and the
    // check below demands the row become `captured` rather than sit at a number nothing uses.
    if (r.reconcilesAt !== undefined) {
      if (!r.captureBlockedBy) {
        wrong.push(
          `${r.key}: states the count reconciles at ${r.reconcilesAt} and does not say what ` +
            `stops it being captured. A reconciling count with no stated blocker is a capture ` +
            `left half-finished`,
        );
      }
      if (r.reconcilesAt !== r.impliedTicks) {
        wrong.push(
          `${r.key}: says the count reconciles at ${r.reconcilesAt}, but ${r.durationSeconds}s / ` +
            `${r.intervalSeconds}s = ${r.impliedTicks}. "Reconciles" means those two agree`,
        );
      }
      if (corrects) {
        wrong.push(
          `${r.key}: is ${r.countVerdict} — the count IS written — and also claims a blocker ` +
            `stopping it being written`,
        );
      }
    }
    if (r.captureBlockedBy !== undefined && r.reconcilesAt === undefined) {
      wrong.push(
        `${r.key}: names something blocking a capture without stating the count that would be ` +
          `captured. A blocker with no number behind it cannot be checked when it is removed`,
      );
    }
  }
  return wrong;
}

/**
 * THE COUNTS TO CORRECT AT MERGE TIME, keyed by entry.
 *
 * Two shapes, both here because both end in the same edit — one component's `hits` replaced by a
 * number that equals the source's own duration divided by its own interval:
 *
 *   - `captured` — the harvest holds 1 because its division rule could not reach the number, and
 *     the page prints it (Rumble R, Viktor R, Nasus R, Wukong R).
 *   - `settled` — the harvest holds the page's own leveling-row multiplier, that multiplier is
 *     stale, and outside evidence says so (Hecarim W, Dr. Mundo W).
 *
 * `merge-proposal.ts` applies these and reports every change, before and after. Nothing else in
 * the pipeline writes a hit count from a hand reading.
 */
export function capturedHitCounts(): ReadonlyMap<string, StatedTotal> {
  return new Map(
    PER_TICK_READS.filter(
      (r) => CORRECTING_COUNT_VERDICTS.includes(r.countVerdict) && r.statedTotal,
    ).map((r) => [r.key, r.statedTotal as StatedTotal]),
  );
}

/** The four read before these 37 (DATA-SOURCES §58.3). Not part of this reading. */
export const ALREADY_READ: ReadonlySet<string> = new Set([
  'Fizz/W/Seastone Trident',
  'Teemo/E/Toxic Shot',
  'Teemo/R/Noxious Trap',
  'Nilah/R/Apotheosis',
]);

/** The same test merge-proposal.ts uses to find a per-tick component. */
export const PER_TICK_LABEL = /per\s*tick/i;

/** The shape this table needs from a harvested ability. Narrower than `CuratedAbility` on purpose:
 *  the reading depends on identity, the component labels and the hit counts, and on nothing else. */
export interface HarvestedShape {
  champion: string;
  slot: string;
  abilityName: string;
  components: Array<{ label?: string | undefined; hits?: number | undefined }>;
}

/**
 * THE TABLE MUST DESCRIBE THE REAL POPULATION, NOT A REMEMBERED ONE.
 *
 * Three ways a hand-read table goes wrong once the data moves under it, and all three are worse
 * than having no table, because a stale row reads exactly like a checked one:
 *   - an entry acquires a per-tick component and nobody reads it;
 *   - a row survives for an entry that no longer has one;
 *   - a hit count changes and the arithmetic in the row now describes nothing.
 */
export function checkAgainstHarvest(
  reads: readonly PerTickRead[],
  abilities: readonly HarvestedShape[],
): string[] {
  const out: string[] = [];
  const id = (a: HarvestedShape): string => `${a.champion}/${a.slot}/${a.abilityName}`;
  const population = abilities.filter(
    (a) => a.components.some((c) => PER_TICK_LABEL.test(c.label ?? '')) && !ALREADY_READ.has(id(a)),
  );
  const tableKeys = new Set(reads.map((r) => r.key));
  for (const a of population) {
    if (!tableKeys.has(id(a))) out.push(`${id(a)}: carries a per-tick component and nobody read it`);
  }
  for (const k of tableKeys) {
    if (!population.some((a) => id(a) === k)) out.push(`${k}: read, but it is not in the population`);
  }
  for (const r of reads) {
    const a = population.find((x) => id(x) === r.key);
    if (!a) continue;
    const actual = a.components
      .filter((c) => PER_TICK_LABEL.test(c.label ?? ''))
      .map((c) => c.hits ?? null);
    if (JSON.stringify(actual) !== JSON.stringify(r.storedHits)) {
      out.push(
        `${r.key}: the reading says hits ${JSON.stringify(r.storedHits)}, the harvest holds ` +
          `${JSON.stringify(actual)}`,
      );
    }
  }
  return out;
}

export interface QuoteCheck {
  key: string;
  found: number;
  missing: string[];
  pageMissing: boolean;
}

/** A cached source page, as `ability-wikitext.json` stores it. */
export interface CachedPage {
  champion: string;
  slot: string;
  abilityName: string;
  wikitext: string;
}

/**
 * PROVE EVERY QUOTE IS REALLY IN THE SOURCE.
 *
 * Each `verbatim` fragment must appear as a literal substring of the ability's cached wikitext.
 * A paraphrase that drifted, or a sentence attributed to the wrong ability, fails here.
 */
export function verifyQuotes(
  reads: readonly PerTickRead[],
  pages: readonly CachedPage[],
): QuoteCheck[] {
  const byKey = new Map(pages.map((p) => [`${p.champion}/${p.slot}/${p.abilityName}`, p.wikitext]));
  return reads.map((r) => {
    const text = byKey.get(r.key);
    if (text === undefined) return { key: r.key, found: 0, missing: r.verbatim, pageMissing: true };
    const missing = r.verbatim.filter((v) => !text.includes(v));
    return { key: r.key, found: r.verbatim.length - missing.length, missing, pageMissing: false };
  });
}

/** Read the wikitext cache. Separated from `verifyQuotes` so the check itself needs no disk. */
export async function loadPages(): Promise<CachedPage[]> {
  const raw = await readFile(join(ROOT, WIKITEXT_CACHE), 'utf8');
  return (JSON.parse(raw) as { pages: CachedPage[] }).pages;
}
